server:
  http:
    addr: 0.0.0.0:8013
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9013
    timeout: 1s
data:
  database:
    driver: postgres
    source: postgres://sibi.t:1323@localhost:5432/fintech?sslmode=disable
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
redis:
  mode: "ring"
  username: ""
  password: ""
  ring:
    address:
       server1: localhost:6379
       server2: localhost:6380
       server3: localhost:6378