// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"BlockAccount/internal/client"
	"BlockAccount/internal/conf"
	"BlockAccount/internal/data"
	"BlockAccount/internal/handler"
	"BlockAccount/internal/server"
	"BlockAccount/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	accountClient := client.AccountClient()
	accountBlockHandler := handler.NewAccountBlockHandler(greeterRepo, accountClient)
	accountBlockServiceService := service.NewAccountBlockServiceService(accountBlockHandler)
	grpcServer := server.NewGRPCServer(confServer, accountBlockServiceService, logger)
	httpServer := server.NewHTTPServer(confServer, accountBlockServiceService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
