// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/helloworld/v1/account.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Create Account
type AccountRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AccountId         int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	CustomerId        int64                  `protobuf:"varint,2,opt,name=customerId,proto3" json:"customerId,omitempty"`
	AccountNumber     int64                  `protobuf:"varint,3,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType       string                 `protobuf:"bytes,4,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Currency          string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status            string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	AvailableBalance  int64                  `protobuf:"varint,7,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	PendingBalance    int64                  `protobuf:"varint,8,opt,name=pendingBalance,proto3" json:"pendingBalance,omitempty"`
	CreditLimit       string                 `protobuf:"bytes,9,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	LastTransactionAt string                 `protobuf:"bytes,12,opt,name=lastTransactionAt,proto3" json:"lastTransactionAt,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AccountRequest) Reset() {
	*x = AccountRequest{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRequest) ProtoMessage() {}

func (x *AccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRequest.ProtoReflect.Descriptor instead.
func (*AccountRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *AccountRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *AccountRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *AccountRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *AccountRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *AccountRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AccountRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AccountRequest) GetAvailableBalance() int64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *AccountRequest) GetPendingBalance() int64 {
	if x != nil {
		return x.PendingBalance
	}
	return 0
}

func (x *AccountRequest) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *AccountRequest) GetLastTransactionAt() string {
	if x != nil {
		return x.LastTransactionAt
	}
	return ""
}

// Account Response
type AccountReply struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AccountId         int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	CustomerId        int64                  `protobuf:"varint,2,opt,name=customerId,proto3" json:"customerId,omitempty"`
	AccountNumber     int64                  `protobuf:"varint,3,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType       string                 `protobuf:"bytes,4,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Currency          string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status            string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	AvailableBalance  int64                  `protobuf:"varint,7,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	PendingBalance    int64                  `protobuf:"varint,8,opt,name=pendingBalance,proto3" json:"pendingBalance,omitempty"`
	CreditLimit       string                 `protobuf:"bytes,9,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	LastTransactionAt string                 `protobuf:"bytes,12,opt,name=lastTransactionAt,proto3" json:"lastTransactionAt,omitempty"`
	Message           string                 `protobuf:"bytes,13,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AccountReply) Reset() {
	*x = AccountReply{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountReply) ProtoMessage() {}

func (x *AccountReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountReply.ProtoReflect.Descriptor instead.
func (*AccountReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *AccountReply) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *AccountReply) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *AccountReply) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *AccountReply) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *AccountReply) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AccountReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AccountReply) GetAvailableBalance() int64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *AccountReply) GetPendingBalance() int64 {
	if x != nil {
		return x.PendingBalance
	}
	return 0
}

func (x *AccountReply) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *AccountReply) GetLastTransactionAt() string {
	if x != nil {
		return x.LastTransactionAt
	}
	return ""
}

func (x *AccountReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Update Account
type UpdateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	CustomerId       int64                  `protobuf:"varint,2,opt,name=customerId,proto3" json:"customerId,omitempty"`
	AccountNumber    int64                  `protobuf:"varint,3,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType      string                 `protobuf:"bytes,4,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Currency         string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	AvailableBalance int64                  `protobuf:"varint,7,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	PendingBalance   int64                  `protobuf:"varint,8,opt,name=pendingBalance,proto3" json:"pendingBalance,omitempty"`
	CreditLimit      string                 `protobuf:"bytes,9,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *UpdateRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *UpdateRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *UpdateRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateRequest) GetAvailableBalance() int64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *UpdateRequest) GetPendingBalance() int64 {
	if x != nil {
		return x.PendingBalance
	}
	return 0
}

func (x *UpdateRequest) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

type UpdateReply struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AccountId         int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	CustomerId        int64                  `protobuf:"varint,2,opt,name=customerId,proto3" json:"customerId,omitempty"`
	AccountNumber     int64                  `protobuf:"varint,3,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType       string                 `protobuf:"bytes,4,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Currency          string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status            string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	AvailableBalance  int64                  `protobuf:"varint,7,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	PendingBalance    int64                  `protobuf:"varint,8,opt,name=pendingBalance,proto3" json:"pendingBalance,omitempty"`
	CreditLimit       string                 `protobuf:"bytes,9,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	LastTransactionAt string                 `protobuf:"bytes,12,opt,name=lastTransactionAt,proto3" json:"lastTransactionAt,omitempty"`
	Message           string                 `protobuf:"bytes,13,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateReply) Reset() {
	*x = UpdateReply{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReply) ProtoMessage() {}

func (x *UpdateReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReply.ProtoReflect.Descriptor instead.
func (*UpdateReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateReply) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateReply) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *UpdateReply) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *UpdateReply) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *UpdateReply) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateReply) GetAvailableBalance() int64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *UpdateReply) GetPendingBalance() int64 {
	if x != nil {
		return x.PendingBalance
	}
	return 0
}

func (x *UpdateReply) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *UpdateReply) GetLastTransactionAt() string {
	if x != nil {
		return x.LastTransactionAt
	}
	return ""
}

func (x *UpdateReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Delete Account
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int64                  `protobuf:"varint,1,opt,name=customerId,proto3" json:"customerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

type DeleteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReply) Reset() {
	*x = DeleteReply{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReply) ProtoMessage() {}

func (x *DeleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReply.ProtoReflect.Descriptor instead.
func (*DeleteReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Get accounts by customerId
type GetCustomerWithIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int64                  `protobuf:"varint,1,opt,name=customerId,proto3" json:"customerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerWithIdRequest) Reset() {
	*x = GetCustomerWithIdRequest{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerWithIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerWithIdRequest) ProtoMessage() {}

func (x *GetCustomerWithIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerWithIdRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerWithIdRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{6}
}

func (x *GetCustomerWithIdRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

type GetCustomerWithIdReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*AccountReply        `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerWithIdReply) Reset() {
	*x = GetCustomerWithIdReply{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerWithIdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerWithIdReply) ProtoMessage() {}

func (x *GetCustomerWithIdReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerWithIdReply.ProtoReflect.Descriptor instead.
func (*GetCustomerWithIdReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{7}
}

func (x *GetCustomerWithIdReply) GetAccounts() []*AccountReply {
	if x != nil {
		return x.Accounts
	}
	return nil
}

// Get accounts by accountId
type AccountIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountIdRequest) Reset() {
	*x = AccountIdRequest{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountIdRequest) ProtoMessage() {}

func (x *AccountIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountIdRequest.ProtoReflect.Descriptor instead.
func (*AccountIdRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{8}
}

func (x *AccountIdRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type AccountIdReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*AccountReply        `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountIdReply) Reset() {
	*x = AccountIdReply{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountIdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountIdReply) ProtoMessage() {}

func (x *AccountIdReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountIdReply.ProtoReflect.Descriptor instead.
func (*AccountIdReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{9}
}

func (x *AccountIdReply) GetAccounts() []*AccountReply {
	if x != nil {
		return x.Accounts
	}
	return nil
}

var File_api_helloworld_v1_account_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_account_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/helloworld/v1/account.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"\xee\x02\n" +
	"\x0eAccountRequest\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12\x1e\n" +
	"\n" +
	"customerId\x18\x02 \x01(\x03R\n" +
	"customerId\x12$\n" +
	"\raccountNumber\x18\x03 \x01(\x03R\raccountNumber\x12 \n" +
	"\vaccountType\x18\x04 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12*\n" +
	"\x10availableBalance\x18\a \x01(\x03R\x10availableBalance\x12&\n" +
	"\x0ependingBalance\x18\b \x01(\x03R\x0ependingBalance\x12 \n" +
	"\vcreditLimit\x18\t \x01(\tR\vcreditLimit\x12,\n" +
	"\x11lastTransactionAt\x18\f \x01(\tR\x11lastTransactionAt\"\x86\x03\n" +
	"\fAccountReply\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12\x1e\n" +
	"\n" +
	"customerId\x18\x02 \x01(\x03R\n" +
	"customerId\x12$\n" +
	"\raccountNumber\x18\x03 \x01(\x03R\raccountNumber\x12 \n" +
	"\vaccountType\x18\x04 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12*\n" +
	"\x10availableBalance\x18\a \x01(\x03R\x10availableBalance\x12&\n" +
	"\x0ependingBalance\x18\b \x01(\x03R\x0ependingBalance\x12 \n" +
	"\vcreditLimit\x18\t \x01(\tR\vcreditLimit\x12,\n" +
	"\x11lastTransactionAt\x18\f \x01(\tR\x11lastTransactionAt\x12\x18\n" +
	"\amessage\x18\r \x01(\tR\amessage\"\xbf\x02\n" +
	"\rUpdateRequest\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12\x1e\n" +
	"\n" +
	"customerId\x18\x02 \x01(\x03R\n" +
	"customerId\x12$\n" +
	"\raccountNumber\x18\x03 \x01(\x03R\raccountNumber\x12 \n" +
	"\vaccountType\x18\x04 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12*\n" +
	"\x10availableBalance\x18\a \x01(\x03R\x10availableBalance\x12&\n" +
	"\x0ependingBalance\x18\b \x01(\x03R\x0ependingBalance\x12 \n" +
	"\vcreditLimit\x18\t \x01(\tR\vcreditLimit\"\x85\x03\n" +
	"\vUpdateReply\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12\x1e\n" +
	"\n" +
	"customerId\x18\x02 \x01(\x03R\n" +
	"customerId\x12$\n" +
	"\raccountNumber\x18\x03 \x01(\x03R\raccountNumber\x12 \n" +
	"\vaccountType\x18\x04 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12*\n" +
	"\x10availableBalance\x18\a \x01(\x03R\x10availableBalance\x12&\n" +
	"\x0ependingBalance\x18\b \x01(\x03R\x0ependingBalance\x12 \n" +
	"\vcreditLimit\x18\t \x01(\tR\vcreditLimit\x12,\n" +
	"\x11lastTransactionAt\x18\f \x01(\tR\x11lastTransactionAt\x12\x18\n" +
	"\amessage\x18\r \x01(\tR\amessage\"/\n" +
	"\rDeleteRequest\x12\x1e\n" +
	"\n" +
	"customerId\x18\x01 \x01(\x03R\n" +
	"customerId\"'\n" +
	"\vDeleteReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\":\n" +
	"\x18GetCustomerWithIdRequest\x12\x1e\n" +
	"\n" +
	"customerId\x18\x01 \x01(\x03R\n" +
	"customerId\"Q\n" +
	"\x16GetCustomerWithIdReply\x127\n" +
	"\baccounts\x18\x01 \x03(\v2\x1b.helloworld.v1.AccountReplyR\baccounts\"0\n" +
	"\x10AccountIdRequest\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\"I\n" +
	"\x0eAccountIdReply\x127\n" +
	"\baccounts\x18\x01 \x03(\v2\x1b.helloworld.v1.AccountReplyR\baccounts2\xc8\x04\n" +
	"\aAccount\x12c\n" +
	"\rCreateAccount\x12\x1d.helloworld.v1.AccountRequest\x1a\x1b.helloworld.v1.AccountReply\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/account\x12n\n" +
	"\rUpdateAccount\x12\x1c.helloworld.v1.UpdateRequest\x1a\x1a.helloworld.v1.UpdateReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*2\x18/v1/account/{customerId}\x12k\n" +
	"\rDeleteAccount\x12\x1c.helloworld.v1.DeleteRequest\x1a\x1a.helloworld.v1.DeleteReply\" \x82\xd3\xe4\x93\x02\x1a*\x18/v1/account/{customerId}\x12\x85\x01\n" +
	"\x11GetCustomerWithId\x12'.helloworld.v1.GetCustomerWithIdRequest\x1a%.helloworld.v1.GetCustomerWithIdReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/account/{customerId}\x12s\n" +
	"\x10GetAccountWithId\x12\x1f.helloworld.v1.AccountIdRequest\x1a\x1d.helloworld.v1.AccountIdReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/account/{accountId}BX\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z#accountservice/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_account_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_account_proto_rawDescData []byte
)

func file_api_helloworld_v1_account_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_account_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_account_proto_rawDesc), len(file_api_helloworld_v1_account_proto_rawDesc)))
	})
	return file_api_helloworld_v1_account_proto_rawDescData
}

var file_api_helloworld_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_helloworld_v1_account_proto_goTypes = []any{
	(*AccountRequest)(nil),           // 0: helloworld.v1.AccountRequest
	(*AccountReply)(nil),             // 1: helloworld.v1.AccountReply
	(*UpdateRequest)(nil),            // 2: helloworld.v1.UpdateRequest
	(*UpdateReply)(nil),              // 3: helloworld.v1.UpdateReply
	(*DeleteRequest)(nil),            // 4: helloworld.v1.DeleteRequest
	(*DeleteReply)(nil),              // 5: helloworld.v1.DeleteReply
	(*GetCustomerWithIdRequest)(nil), // 6: helloworld.v1.GetCustomerWithIdRequest
	(*GetCustomerWithIdReply)(nil),   // 7: helloworld.v1.GetCustomerWithIdReply
	(*AccountIdRequest)(nil),         // 8: helloworld.v1.AccountIdRequest
	(*AccountIdReply)(nil),           // 9: helloworld.v1.AccountIdReply
}
var file_api_helloworld_v1_account_proto_depIdxs = []int32{
	1, // 0: helloworld.v1.GetCustomerWithIdReply.accounts:type_name -> helloworld.v1.AccountReply
	1, // 1: helloworld.v1.AccountIdReply.accounts:type_name -> helloworld.v1.AccountReply
	0, // 2: helloworld.v1.Account.CreateAccount:input_type -> helloworld.v1.AccountRequest
	2, // 3: helloworld.v1.Account.UpdateAccount:input_type -> helloworld.v1.UpdateRequest
	4, // 4: helloworld.v1.Account.DeleteAccount:input_type -> helloworld.v1.DeleteRequest
	6, // 5: helloworld.v1.Account.GetCustomerWithId:input_type -> helloworld.v1.GetCustomerWithIdRequest
	8, // 6: helloworld.v1.Account.GetAccountWithId:input_type -> helloworld.v1.AccountIdRequest
	1, // 7: helloworld.v1.Account.CreateAccount:output_type -> helloworld.v1.AccountReply
	3, // 8: helloworld.v1.Account.UpdateAccount:output_type -> helloworld.v1.UpdateReply
	5, // 9: helloworld.v1.Account.DeleteAccount:output_type -> helloworld.v1.DeleteReply
	7, // 10: helloworld.v1.Account.GetCustomerWithId:output_type -> helloworld.v1.GetCustomerWithIdReply
	9, // 11: helloworld.v1.Account.GetAccountWithId:output_type -> helloworld.v1.AccountIdReply
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_account_proto_init() }
func file_api_helloworld_v1_account_proto_init() {
	if File_api_helloworld_v1_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_account_proto_rawDesc), len(file_api_helloworld_v1_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_account_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_account_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_account_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_account_proto = out.File
	file_api_helloworld_v1_account_proto_goTypes = nil
	file_api_helloworld_v1_account_proto_depIdxs = nil
}
