// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/helloworld/v1/card.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        int64                  `protobuf:"varint,1,opt,name=cardId,proto3" json:"cardId,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Cardnumber    string                 `protobuf:"bytes,3,opt,name=cardnumber,proto3" json:"cardnumber,omitempty"`
	Cardtype      string                 `protobuf:"bytes,4,opt,name=cardtype,proto3" json:"cardtype,omitempty"`
	Expirydate    string                 `protobuf:"bytes,5,opt,name=expirydate,proto3" json:"expirydate,omitempty"`
	Dailylimit    int64                  `protobuf:"varint,6,opt,name=dailylimit,proto3" json:"dailylimit,omitempty"`
	Monthlylimit  int64                  `protobuf:"varint,7,opt,name=monthlylimit,proto3" json:"monthlylimit,omitempty"`
	Pinattempts   int64                  `protobuf:"varint,8,opt,name=pinattempts,proto3" json:"pinattempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_api_helloworld_v1_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_card_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *CreateRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateRequest) GetCardnumber() string {
	if x != nil {
		return x.Cardnumber
	}
	return ""
}

func (x *CreateRequest) GetCardtype() string {
	if x != nil {
		return x.Cardtype
	}
	return ""
}

func (x *CreateRequest) GetExpirydate() string {
	if x != nil {
		return x.Expirydate
	}
	return ""
}

func (x *CreateRequest) GetDailylimit() int64 {
	if x != nil {
		return x.Dailylimit
	}
	return 0
}

func (x *CreateRequest) GetMonthlylimit() int64 {
	if x != nil {
		return x.Monthlylimit
	}
	return 0
}

func (x *CreateRequest) GetPinattempts() int64 {
	if x != nil {
		return x.Pinattempts
	}
	return 0
}

type CreateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	CardId        int64                  `protobuf:"varint,1,opt,name=cardId,proto3" json:"cardId,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Cardnumber    string                 `protobuf:"bytes,3,opt,name=cardnumber,proto3" json:"cardnumber,omitempty"`
	Cardtype      string                 `protobuf:"bytes,4,opt,name=cardtype,proto3" json:"cardtype,omitempty"`
	Expirydate    string                 `protobuf:"bytes,5,opt,name=expirydate,proto3" json:"expirydate,omitempty"`
	Dailylimit    int64                  `protobuf:"varint,6,opt,name=dailylimit,proto3" json:"dailylimit,omitempty"`
	Monthlylimit  int64                  `protobuf:"varint,7,opt,name=monthlylimit,proto3" json:"monthlylimit,omitempty"`
	Pinattempts   int64                  `protobuf:"varint,8,opt,name=pinattempts,proto3" json:"pinattempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReply) Reset() {
	*x = CreateReply{}
	mi := &file_api_helloworld_v1_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReply) ProtoMessage() {}

func (x *CreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReply.ProtoReflect.Descriptor instead.
func (*CreateReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_card_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateReply) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *CreateReply) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateReply) GetCardnumber() string {
	if x != nil {
		return x.Cardnumber
	}
	return ""
}

func (x *CreateReply) GetCardtype() string {
	if x != nil {
		return x.Cardtype
	}
	return ""
}

func (x *CreateReply) GetExpirydate() string {
	if x != nil {
		return x.Expirydate
	}
	return ""
}

func (x *CreateReply) GetDailylimit() int64 {
	if x != nil {
		return x.Dailylimit
	}
	return 0
}

func (x *CreateReply) GetMonthlylimit() int64 {
	if x != nil {
		return x.Monthlylimit
	}
	return 0
}

func (x *CreateReply) GetPinattempts() int64 {
	if x != nil {
		return x.Pinattempts
	}
	return 0
}

type UpdateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        int64                  `protobuf:"varint,1,opt,name=cardId,proto3" json:"cardId,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Cardnumber    string                 `protobuf:"bytes,3,opt,name=cardnumber,proto3" json:"cardnumber,omitempty"`
	Cardtype      string                 `protobuf:"bytes,4,opt,name=cardtype,proto3" json:"cardtype,omitempty"`
	Dailylimit    int64                  `protobuf:"varint,6,opt,name=dailylimit,proto3" json:"dailylimit,omitempty"`
	Monthlylimit  int64                  `protobuf:"varint,7,opt,name=monthlylimit,proto3" json:"monthlylimit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardRequest) Reset() {
	*x = UpdateCardRequest{}
	mi := &file_api_helloworld_v1_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardRequest) ProtoMessage() {}

func (x *UpdateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardRequest.ProtoReflect.Descriptor instead.
func (*UpdateCardRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_card_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCardRequest) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *UpdateCardRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateCardRequest) GetCardnumber() string {
	if x != nil {
		return x.Cardnumber
	}
	return ""
}

func (x *UpdateCardRequest) GetCardtype() string {
	if x != nil {
		return x.Cardtype
	}
	return ""
}

func (x *UpdateCardRequest) GetDailylimit() int64 {
	if x != nil {
		return x.Dailylimit
	}
	return 0
}

func (x *UpdateCardRequest) GetMonthlylimit() int64 {
	if x != nil {
		return x.Monthlylimit
	}
	return 0
}

type UpdateCardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Display       []*CreateReply         `protobuf:"bytes,2,rep,name=display,proto3" json:"display,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardReply) Reset() {
	*x = UpdateCardReply{}
	mi := &file_api_helloworld_v1_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardReply) ProtoMessage() {}

func (x *UpdateCardReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardReply.ProtoReflect.Descriptor instead.
func (*UpdateCardReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_card_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCardReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateCardReply) GetDisplay() []*CreateReply {
	if x != nil {
		return x.Display
	}
	return nil
}

type DeleteCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        int64                  `protobuf:"varint,1,opt,name=cardId,proto3" json:"cardId,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardRequest) Reset() {
	*x = DeleteCardRequest{}
	mi := &file_api_helloworld_v1_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardRequest) ProtoMessage() {}

func (x *DeleteCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteCardRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_card_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCardRequest) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *DeleteCardRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type DeleteCardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardReply) Reset() {
	*x = DeleteCardReply{}
	mi := &file_api_helloworld_v1_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardReply) ProtoMessage() {}

func (x *DeleteCardReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardReply.ProtoReflect.Descriptor instead.
func (*DeleteCardReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_card_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCardReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FindByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        int64                  `protobuf:"varint,1,opt,name=cardId,proto3" json:"cardId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdRequest) Reset() {
	*x = FindByIdRequest{}
	mi := &file_api_helloworld_v1_card_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdRequest) ProtoMessage() {}

func (x *FindByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_card_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdRequest.ProtoReflect.Descriptor instead.
func (*FindByIdRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_card_proto_rawDescGZIP(), []int{6}
}

func (x *FindByIdRequest) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

type FindByIdReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Display       []*CreateReply         `protobuf:"bytes,1,rep,name=display,proto3" json:"display,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdReply) Reset() {
	*x = FindByIdReply{}
	mi := &file_api_helloworld_v1_card_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdReply) ProtoMessage() {}

func (x *FindByIdReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_card_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdReply.ProtoReflect.Descriptor instead.
func (*FindByIdReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_card_proto_rawDescGZIP(), []int{7}
}

func (x *FindByIdReply) GetDisplay() []*CreateReply {
	if x != nil {
		return x.Display
	}
	return nil
}

var File_api_helloworld_v1_card_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_card_proto_rawDesc = "" +
	"\n" +
	"\x1capi/helloworld/v1/card.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"\x87\x02\n" +
	"\rCreateRequest\x12\x16\n" +
	"\x06cardId\x18\x01 \x01(\x03R\x06cardId\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\x12\x1e\n" +
	"\n" +
	"cardnumber\x18\x03 \x01(\tR\n" +
	"cardnumber\x12\x1a\n" +
	"\bcardtype\x18\x04 \x01(\tR\bcardtype\x12\x1e\n" +
	"\n" +
	"expirydate\x18\x05 \x01(\tR\n" +
	"expirydate\x12\x1e\n" +
	"\n" +
	"dailylimit\x18\x06 \x01(\x03R\n" +
	"dailylimit\x12\"\n" +
	"\fmonthlylimit\x18\a \x01(\x03R\fmonthlylimit\x12 \n" +
	"\vpinattempts\x18\b \x01(\x03R\vpinattempts\"\x9f\x02\n" +
	"\vCreateReply\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessage\x12\x16\n" +
	"\x06cardId\x18\x01 \x01(\x03R\x06cardId\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\x12\x1e\n" +
	"\n" +
	"cardnumber\x18\x03 \x01(\tR\n" +
	"cardnumber\x12\x1a\n" +
	"\bcardtype\x18\x04 \x01(\tR\bcardtype\x12\x1e\n" +
	"\n" +
	"expirydate\x18\x05 \x01(\tR\n" +
	"expirydate\x12\x1e\n" +
	"\n" +
	"dailylimit\x18\x06 \x01(\x03R\n" +
	"dailylimit\x12\"\n" +
	"\fmonthlylimit\x18\a \x01(\x03R\fmonthlylimit\x12 \n" +
	"\vpinattempts\x18\b \x01(\x03R\vpinattempts\"\xc9\x01\n" +
	"\x11UpdateCardRequest\x12\x16\n" +
	"\x06cardId\x18\x01 \x01(\x03R\x06cardId\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\x12\x1e\n" +
	"\n" +
	"cardnumber\x18\x03 \x01(\tR\n" +
	"cardnumber\x12\x1a\n" +
	"\bcardtype\x18\x04 \x01(\tR\bcardtype\x12\x1e\n" +
	"\n" +
	"dailylimit\x18\x06 \x01(\x03R\n" +
	"dailylimit\x12\"\n" +
	"\fmonthlylimit\x18\a \x01(\x03R\fmonthlylimit\"a\n" +
	"\x0fUpdateCardReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x124\n" +
	"\adisplay\x18\x02 \x03(\v2\x1a.helloworld.v1.CreateReplyR\adisplay\"I\n" +
	"\x11DeleteCardRequest\x12\x16\n" +
	"\x06cardId\x18\x01 \x01(\x03R\x06cardId\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\x03R\taccountId\"+\n" +
	"\x0fDeleteCardReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\")\n" +
	"\x0fFindByIdRequest\x12\x16\n" +
	"\x06cardId\x18\x01 \x01(\x03R\x06cardId\"E\n" +
	"\rFindByIdReply\x124\n" +
	"\adisplay\x18\x01 \x03(\v2\x1a.helloworld.v1.CreateReplyR\adisplay2\xd0\x03\n" +
	"\x04Card\x12f\n" +
	"\n" +
	"CreateCard\x12\x1c.helloworld.v1.CreateRequest\x1a\x1a.helloworld.v1.CreateReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/helloworld/card\x12w\n" +
	"\n" +
	"UpdateCard\x12 .helloworld.v1.UpdateCardRequest\x1a\x1e.helloworld.v1.UpdateCardReply\"'\x82\xd3\xe4\x93\x02!:\x01*2\x1c/v1/helloworld/card/{cardId}\x12t\n" +
	"\n" +
	"DeleteCard\x12 .helloworld.v1.DeleteCardRequest\x1a\x1e.helloworld.v1.DeleteCardReply\"$\x82\xd3\xe4\x93\x02\x1e*\x1c/v1/helloworld/card/{cardId}\x12q\n" +
	"\vDisplayCard\x12\x1e.helloworld.v1.FindByIdRequest\x1a\x1c.helloworld.v1.FindByIdReply\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/helloworld/card/{cardId}BU\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z cardservice/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_card_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_card_proto_rawDescData []byte
)

func file_api_helloworld_v1_card_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_card_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_card_proto_rawDesc), len(file_api_helloworld_v1_card_proto_rawDesc)))
	})
	return file_api_helloworld_v1_card_proto_rawDescData
}

var file_api_helloworld_v1_card_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_helloworld_v1_card_proto_goTypes = []any{
	(*CreateRequest)(nil),     // 0: helloworld.v1.CreateRequest
	(*CreateReply)(nil),       // 1: helloworld.v1.CreateReply
	(*UpdateCardRequest)(nil), // 2: helloworld.v1.UpdateCardRequest
	(*UpdateCardReply)(nil),   // 3: helloworld.v1.UpdateCardReply
	(*DeleteCardRequest)(nil), // 4: helloworld.v1.DeleteCardRequest
	(*DeleteCardReply)(nil),   // 5: helloworld.v1.DeleteCardReply
	(*FindByIdRequest)(nil),   // 6: helloworld.v1.FindByIdRequest
	(*FindByIdReply)(nil),     // 7: helloworld.v1.FindByIdReply
}
var file_api_helloworld_v1_card_proto_depIdxs = []int32{
	1, // 0: helloworld.v1.UpdateCardReply.display:type_name -> helloworld.v1.CreateReply
	1, // 1: helloworld.v1.FindByIdReply.display:type_name -> helloworld.v1.CreateReply
	0, // 2: helloworld.v1.Card.CreateCard:input_type -> helloworld.v1.CreateRequest
	2, // 3: helloworld.v1.Card.UpdateCard:input_type -> helloworld.v1.UpdateCardRequest
	4, // 4: helloworld.v1.Card.DeleteCard:input_type -> helloworld.v1.DeleteCardRequest
	6, // 5: helloworld.v1.Card.DisplayCard:input_type -> helloworld.v1.FindByIdRequest
	1, // 6: helloworld.v1.Card.CreateCard:output_type -> helloworld.v1.CreateReply
	3, // 7: helloworld.v1.Card.UpdateCard:output_type -> helloworld.v1.UpdateCardReply
	5, // 8: helloworld.v1.Card.DeleteCard:output_type -> helloworld.v1.DeleteCardReply
	7, // 9: helloworld.v1.Card.DisplayCard:output_type -> helloworld.v1.FindByIdReply
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_card_proto_init() }
func file_api_helloworld_v1_card_proto_init() {
	if File_api_helloworld_v1_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_card_proto_rawDesc), len(file_api_helloworld_v1_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_card_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_card_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_card_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_card_proto = out.File
	file_api_helloworld_v1_card_proto_goTypes = nil
	file_api_helloworld_v1_card_proto_depIdxs = nil
}
