// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/helloworld/v1/greeter.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Customer messages
type CreateCustomerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CustomerId     int64                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CustomerNumber string                 `protobuf:"bytes,2,opt,name=customer_number,json=customerNumber,proto3" json:"customer_number,omitempty"`
	FirstName      string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email          string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone          string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	DateOfBirth    string                 `protobuf:"bytes,7,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Status         string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	KycStatus      string                 `protobuf:"bytes,9,opt,name=kyc_status,json=kycStatus,proto3" json:"kyc_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCustomerRequest) Reset() {
	*x = CreateCustomerRequest{}
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerRequest) ProtoMessage() {}

func (x *CreateCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerRequest.ProtoReflect.Descriptor instead.
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCustomerRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *CreateCustomerRequest) GetCustomerNumber() string {
	if x != nil {
		return x.CustomerNumber
	}
	return ""
}

func (x *CreateCustomerRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateCustomerRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateCustomerRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateCustomerRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateCustomerRequest) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *CreateCustomerRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateCustomerRequest) GetKycStatus() string {
	if x != nil {
		return x.KycStatus
	}
	return ""
}

type CreateCustomerReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Message        string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	CustomerId     int64                  `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CustomerNumber string                 `protobuf:"bytes,3,opt,name=customer_number,json=customerNumber,proto3" json:"customer_number,omitempty"`
	FirstName      string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email          string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phone          string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	DateOfBirth    string                 `protobuf:"bytes,8,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Status         string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	KycStatus      string                 `protobuf:"bytes,10,opt,name=kyc_status,json=kycStatus,proto3" json:"kyc_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCustomerReply) Reset() {
	*x = CreateCustomerReply{}
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerReply) ProtoMessage() {}

func (x *CreateCustomerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerReply.ProtoReflect.Descriptor instead.
func (*CreateCustomerReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCustomerReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateCustomerReply) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *CreateCustomerReply) GetCustomerNumber() string {
	if x != nil {
		return x.CustomerNumber
	}
	return ""
}

func (x *CreateCustomerReply) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateCustomerReply) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateCustomerReply) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateCustomerReply) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateCustomerReply) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *CreateCustomerReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateCustomerReply) GetKycStatus() string {
	if x != nil {
		return x.KycStatus
	}
	return ""
}

type UpdateCustomerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CustomerId     int64                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CustomerNumber string                 `protobuf:"bytes,2,opt,name=customer_number,json=customerNumber,proto3" json:"customer_number,omitempty"`
	FirstName      string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email          string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone          string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	DateOfBirth    string                 `protobuf:"bytes,7,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Status         string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	KycStatus      string                 `protobuf:"bytes,9,opt,name=kyc_status,json=kycStatus,proto3" json:"kyc_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateCustomerRequest) Reset() {
	*x = UpdateCustomerRequest{}
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCustomerRequest) ProtoMessage() {}

func (x *UpdateCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCustomerRequest.ProtoReflect.Descriptor instead.
func (*UpdateCustomerRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_greeter_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCustomerRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *UpdateCustomerRequest) GetCustomerNumber() string {
	if x != nil {
		return x.CustomerNumber
	}
	return ""
}

func (x *UpdateCustomerRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateCustomerRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateCustomerRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateCustomerRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateCustomerRequest) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *UpdateCustomerRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateCustomerRequest) GetKycStatus() string {
	if x != nil {
		return x.KycStatus
	}
	return ""
}

type AccountDetails struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AccountId         int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CustomerId        int64                  `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AccountNumber     int64                  `protobuf:"varint,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	AccountType       string                 `protobuf:"bytes,4,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Currency          string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status            string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	AvailableBalance  int64                  `protobuf:"varint,7,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	PendingBalance    int64                  `protobuf:"varint,8,opt,name=pending_balance,json=pendingBalance,proto3" json:"pending_balance,omitempty"`
	CreditLimit       string                 `protobuf:"bytes,9,opt,name=credit_limit,json=creditLimit,proto3" json:"credit_limit,omitempty"`
	LastTransactionAt string                 `protobuf:"bytes,10,opt,name=last_transaction_at,json=lastTransactionAt,proto3" json:"last_transaction_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AccountDetails) Reset() {
	*x = AccountDetails{}
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountDetails) ProtoMessage() {}

func (x *AccountDetails) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountDetails.ProtoReflect.Descriptor instead.
func (*AccountDetails) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_greeter_proto_rawDescGZIP(), []int{3}
}

func (x *AccountDetails) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *AccountDetails) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *AccountDetails) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *AccountDetails) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *AccountDetails) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AccountDetails) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AccountDetails) GetAvailableBalance() int64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *AccountDetails) GetPendingBalance() int64 {
	if x != nil {
		return x.PendingBalance
	}
	return 0
}

func (x *AccountDetails) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *AccountDetails) GetLastTransactionAt() string {
	if x != nil {
		return x.LastTransactionAt
	}
	return ""
}

type UpdateCustomerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Display       []*CreateCustomerReply `protobuf:"bytes,2,rep,name=display,proto3" json:"display,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCustomerReply) Reset() {
	*x = UpdateCustomerReply{}
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCustomerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCustomerReply) ProtoMessage() {}

func (x *UpdateCustomerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCustomerReply.ProtoReflect.Descriptor instead.
func (*UpdateCustomerReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_greeter_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCustomerReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateCustomerReply) GetDisplay() []*CreateCustomerReply {
	if x != nil {
		return x.Display
	}
	return nil
}

type DeleteCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int64                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCustomerRequest) Reset() {
	*x = DeleteCustomerRequest{}
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCustomerRequest) ProtoMessage() {}

func (x *DeleteCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCustomerRequest.ProtoReflect.Descriptor instead.
func (*DeleteCustomerRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_greeter_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCustomerRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

type DeleteCustomerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCustomerReply) Reset() {
	*x = DeleteCustomerReply{}
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCustomerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCustomerReply) ProtoMessage() {}

func (x *DeleteCustomerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCustomerReply.ProtoReflect.Descriptor instead.
func (*DeleteCustomerReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_greeter_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCustomerReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FindCustomerByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int64                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCustomerByIdRequest) Reset() {
	*x = FindCustomerByIdRequest{}
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCustomerByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCustomerByIdRequest) ProtoMessage() {}

func (x *FindCustomerByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCustomerByIdRequest.ProtoReflect.Descriptor instead.
func (*FindCustomerByIdRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_greeter_proto_rawDescGZIP(), []int{7}
}

func (x *FindCustomerByIdRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

type FindCustomerByIdReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Display       []*CreateCustomerReply `protobuf:"bytes,1,rep,name=display,proto3" json:"display,omitempty"`
	Acc           []*AccountDetails      `protobuf:"bytes,2,rep,name=acc,proto3" json:"acc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCustomerByIdReply) Reset() {
	*x = FindCustomerByIdReply{}
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCustomerByIdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCustomerByIdReply) ProtoMessage() {}

func (x *FindCustomerByIdReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCustomerByIdReply.ProtoReflect.Descriptor instead.
func (*FindCustomerByIdReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_greeter_proto_rawDescGZIP(), []int{8}
}

func (x *FindCustomerByIdReply) GetDisplay() []*CreateCustomerReply {
	if x != nil {
		return x.Display
	}
	return nil
}

func (x *FindCustomerByIdReply) GetAcc() []*AccountDetails {
	if x != nil {
		return x.Acc
	}
	return nil
}

var File_api_helloworld_v1_greeter_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_greeter_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/helloworld/v1/greeter.proto\x12\x12customermanager.v1\x1a\x1cgoogle/api/annotations.proto\"\xa4\x02\n" +
	"\x15CreateCustomerRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x03R\n" +
	"customerId\x12'\n" +
	"\x0fcustomer_number\x18\x02 \x01(\tR\x0ecustomerNumber\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\"\n" +
	"\rdate_of_birth\x18\a \x01(\tR\vdateOfBirth\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"kyc_status\x18\t \x01(\tR\tkycStatus\"\xbc\x02\n" +
	"\x13CreateCustomerReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\x03R\n" +
	"customerId\x12'\n" +
	"\x0fcustomer_number\x18\x03 \x01(\tR\x0ecustomerNumber\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12\"\n" +
	"\rdate_of_birth\x18\b \x01(\tR\vdateOfBirth\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"kyc_status\x18\n" +
	" \x01(\tR\tkycStatus\"\xa4\x02\n" +
	"\x15UpdateCustomerRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x03R\n" +
	"customerId\x12'\n" +
	"\x0fcustomer_number\x18\x02 \x01(\tR\x0ecustomerNumber\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\"\n" +
	"\rdate_of_birth\x18\a \x01(\tR\vdateOfBirth\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"kyc_status\x18\t \x01(\tR\tkycStatus\"\xf7\x02\n" +
	"\x0eAccountDetails\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\x03R\n" +
	"customerId\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\x03R\raccountNumber\x12!\n" +
	"\faccount_type\x18\x04 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12+\n" +
	"\x11available_balance\x18\a \x01(\x03R\x10availableBalance\x12'\n" +
	"\x0fpending_balance\x18\b \x01(\x03R\x0ependingBalance\x12!\n" +
	"\fcredit_limit\x18\t \x01(\tR\vcreditLimit\x12.\n" +
	"\x13last_transaction_at\x18\n" +
	" \x01(\tR\x11lastTransactionAt\"r\n" +
	"\x13UpdateCustomerReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12A\n" +
	"\adisplay\x18\x02 \x03(\v2'.customermanager.v1.CreateCustomerReplyR\adisplay\"8\n" +
	"\x15DeleteCustomerRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x03R\n" +
	"customerId\"/\n" +
	"\x13DeleteCustomerReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\":\n" +
	"\x17FindCustomerByIdRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x03R\n" +
	"customerId\"\x90\x01\n" +
	"\x15FindCustomerByIdReply\x12A\n" +
	"\adisplay\x18\x01 \x03(\v2'.customermanager.v1.CreateCustomerReplyR\adisplay\x124\n" +
	"\x03acc\x18\x02 \x03(\v2\".customermanager.v1.AccountDetailsR\x03acc2\xa6\x04\n" +
	"\x0fCustomerManager\x12~\n" +
	"\x0eCreateCustomer\x12).customermanager.v1.CreateCustomerRequest\x1a'.customermanager.v1.CreateCustomerReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/customers\x12o\n" +
	"\x0eUpdateCustomer\x12).customermanager.v1.UpdateCustomerRequest\x1a'.customermanager.v1.UpdateCustomerReply\"\t\x82\xd3\xe4\x93\x02\x03:\x01*\x12\x89\x01\n" +
	"\x0eDeleteCustomer\x12).customermanager.v1.DeleteCustomerRequest\x1a'.customermanager.v1.DeleteCustomerReply\"#\x82\xd3\xe4\x93\x02\x1d*\x1b/v1/customers/{customer_id}\x12\x95\x01\n" +
	"\x0fDisplayCustomer\x12+.customermanager.v1.FindCustomerByIdRequest\x1a).customermanager.v1.FindCustomerByIdReply\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/customers/number/{customer_id}Bh\n" +
	"!dev.kratos.api.customermanager.v1B\x16CustomerManagerProtoV1P\x01Z)customermanager/api/customermanager/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_greeter_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_greeter_proto_rawDescData []byte
)

func file_api_helloworld_v1_greeter_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_greeter_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_greeter_proto_rawDesc), len(file_api_helloworld_v1_greeter_proto_rawDesc)))
	})
	return file_api_helloworld_v1_greeter_proto_rawDescData
}

var file_api_helloworld_v1_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_helloworld_v1_greeter_proto_goTypes = []any{
	(*CreateCustomerRequest)(nil),   // 0: customermanager.v1.CreateCustomerRequest
	(*CreateCustomerReply)(nil),     // 1: customermanager.v1.CreateCustomerReply
	(*UpdateCustomerRequest)(nil),   // 2: customermanager.v1.UpdateCustomerRequest
	(*AccountDetails)(nil),          // 3: customermanager.v1.AccountDetails
	(*UpdateCustomerReply)(nil),     // 4: customermanager.v1.UpdateCustomerReply
	(*DeleteCustomerRequest)(nil),   // 5: customermanager.v1.DeleteCustomerRequest
	(*DeleteCustomerReply)(nil),     // 6: customermanager.v1.DeleteCustomerReply
	(*FindCustomerByIdRequest)(nil), // 7: customermanager.v1.FindCustomerByIdRequest
	(*FindCustomerByIdReply)(nil),   // 8: customermanager.v1.FindCustomerByIdReply
}
var file_api_helloworld_v1_greeter_proto_depIdxs = []int32{
	1, // 0: customermanager.v1.UpdateCustomerReply.display:type_name -> customermanager.v1.CreateCustomerReply
	1, // 1: customermanager.v1.FindCustomerByIdReply.display:type_name -> customermanager.v1.CreateCustomerReply
	3, // 2: customermanager.v1.FindCustomerByIdReply.acc:type_name -> customermanager.v1.AccountDetails
	0, // 3: customermanager.v1.CustomerManager.CreateCustomer:input_type -> customermanager.v1.CreateCustomerRequest
	2, // 4: customermanager.v1.CustomerManager.UpdateCustomer:input_type -> customermanager.v1.UpdateCustomerRequest
	5, // 5: customermanager.v1.CustomerManager.DeleteCustomer:input_type -> customermanager.v1.DeleteCustomerRequest
	7, // 6: customermanager.v1.CustomerManager.DisplayCustomer:input_type -> customermanager.v1.FindCustomerByIdRequest
	1, // 7: customermanager.v1.CustomerManager.CreateCustomer:output_type -> customermanager.v1.CreateCustomerReply
	4, // 8: customermanager.v1.CustomerManager.UpdateCustomer:output_type -> customermanager.v1.UpdateCustomerReply
	6, // 9: customermanager.v1.CustomerManager.DeleteCustomer:output_type -> customermanager.v1.DeleteCustomerReply
	8, // 10: customermanager.v1.CustomerManager.DisplayCustomer:output_type -> customermanager.v1.FindCustomerByIdReply
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_greeter_proto_init() }
func file_api_helloworld_v1_greeter_proto_init() {
	if File_api_helloworld_v1_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_greeter_proto_rawDesc), len(file_api_helloworld_v1_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_greeter_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_greeter_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_greeter_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_greeter_proto = out.File
	file_api_helloworld_v1_greeter_proto_goTypes = nil
	file_api_helloworld_v1_greeter_proto_depIdxs = nil
}
