// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v5.29.3
// source: api/helloworld/v1/greeter.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationNotificationCreateNotification = "/helloworld.v1.Notification/CreateNotification"
const OperationNotificationPaymentNotification = "/helloworld.v1.Notification/PaymentNotification"

type NotificationHTTPServer interface {
	// CreateNotification Sends a greeting
	CreateNotification(context.Context, *RequestNotification) (*ReplyNotification, error)
	PaymentNotification(context.Context, *RequestPaymentDetails) (*ReplyPaymentDetails, error)
}

func RegisterNotificationHTTPServer(s *http.Server, srv NotificationHTTPServer) {
	r := s.Route("/")
	r.POST("/alert/notification", _Notification_CreateNotification0_HTTP_Handler(srv))
	r.POST("/alert/notification/payment", _Notification_PaymentNotification0_HTTP_Handler(srv))
}

func _Notification_CreateNotification0_HTTP_Handler(srv NotificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RequestNotification
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotificationCreateNotification)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateNotification(ctx, req.(*RequestNotification))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReplyNotification)
		return ctx.Result(200, reply)
	}
}

func _Notification_PaymentNotification0_HTTP_Handler(srv NotificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RequestPaymentDetails
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotificationPaymentNotification)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PaymentNotification(ctx, req.(*RequestPaymentDetails))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReplyPaymentDetails)
		return ctx.Result(200, reply)
	}
}

type NotificationHTTPClient interface {
	CreateNotification(ctx context.Context, req *RequestNotification, opts ...http.CallOption) (rsp *ReplyNotification, err error)
	PaymentNotification(ctx context.Context, req *RequestPaymentDetails, opts ...http.CallOption) (rsp *ReplyPaymentDetails, err error)
}

type NotificationHTTPClientImpl struct {
	cc *http.Client
}

func NewNotificationHTTPClient(client *http.Client) NotificationHTTPClient {
	return &NotificationHTTPClientImpl{client}
}

func (c *NotificationHTTPClientImpl) CreateNotification(ctx context.Context, in *RequestNotification, opts ...http.CallOption) (*ReplyNotification, error) {
	var out ReplyNotification
	pattern := "/alert/notification"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationNotificationCreateNotification))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *NotificationHTTPClientImpl) PaymentNotification(ctx context.Context, in *RequestPaymentDetails, opts ...http.CallOption) (*ReplyPaymentDetails, error) {
	var out ReplyPaymentDetails
	pattern := "/alert/notification/payment"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationNotificationPaymentNotification))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
