// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/helloworld/v1/greeter.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type RequestNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestNotification) Reset() {
	*x = RequestNotification{}
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestNotification) ProtoMessage() {}

func (x *RequestNotification) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestNotification.ProtoReflect.Descriptor instead.
func (*RequestNotification) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *RequestNotification) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// The response message containing the greetings
type ReplyNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      string                 `protobuf:"bytes,1,opt,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyNotification) Reset() {
	*x = ReplyNotification{}
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyNotification) ProtoMessage() {}

func (x *ReplyNotification) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyNotification.ProtoReflect.Descriptor instead.
func (*ReplyNotification) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *ReplyNotification) GetMessages() string {
	if x != nil {
		return x.Messages
	}
	return ""
}

type RequestPaymentDetails struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PaymentId         int64                  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	FromAccountId     int64                  `protobuf:"varint,2,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId       int64                  `protobuf:"varint,3,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	PaymentType       string                 `protobuf:"bytes,4,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	Amount            int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency          string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status            string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	PaymentMethod     string                 `protobuf:"bytes,8,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	ReferenceNumber   string                 `protobuf:"bytes,9,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	ExternalReference string                 `protobuf:"bytes,10,opt,name=external_reference,json=externalReference,proto3" json:"external_reference,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RequestPaymentDetails) Reset() {
	*x = RequestPaymentDetails{}
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPaymentDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPaymentDetails) ProtoMessage() {}

func (x *RequestPaymentDetails) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPaymentDetails.ProtoReflect.Descriptor instead.
func (*RequestPaymentDetails) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_greeter_proto_rawDescGZIP(), []int{2}
}

func (x *RequestPaymentDetails) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *RequestPaymentDetails) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *RequestPaymentDetails) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *RequestPaymentDetails) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *RequestPaymentDetails) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RequestPaymentDetails) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RequestPaymentDetails) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RequestPaymentDetails) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *RequestPaymentDetails) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *RequestPaymentDetails) GetExternalReference() string {
	if x != nil {
		return x.ExternalReference
	}
	return ""
}

type ReplyPaymentDetails struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PaymentId         int64                  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	FromAccountId     int64                  `protobuf:"varint,2,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId       int64                  `protobuf:"varint,3,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	PaymentType       string                 `protobuf:"bytes,4,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	Amount            int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency          string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status            string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	PaymentMethod     string                 `protobuf:"bytes,8,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	ReferenceNumber   string                 `protobuf:"bytes,9,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	ExternalReference string                 `protobuf:"bytes,10,opt,name=external_reference,json=externalReference,proto3" json:"external_reference,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReplyPaymentDetails) Reset() {
	*x = ReplyPaymentDetails{}
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyPaymentDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyPaymentDetails) ProtoMessage() {}

func (x *ReplyPaymentDetails) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyPaymentDetails.ProtoReflect.Descriptor instead.
func (*ReplyPaymentDetails) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_greeter_proto_rawDescGZIP(), []int{3}
}

func (x *ReplyPaymentDetails) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *ReplyPaymentDetails) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *ReplyPaymentDetails) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *ReplyPaymentDetails) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *ReplyPaymentDetails) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ReplyPaymentDetails) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ReplyPaymentDetails) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReplyPaymentDetails) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *ReplyPaymentDetails) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *ReplyPaymentDetails) GetExternalReference() string {
	if x != nil {
		return x.ExternalReference
	}
	return ""
}

var File_api_helloworld_v1_greeter_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_greeter_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/helloworld/v1/greeter.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"+\n" +
	"\x13RequestNotification\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"/\n" +
	"\x11ReplyNotification\x12\x1a\n" +
	"\bmessages\x18\x01 \x01(\tR\bmessages\"\xf2\x02\n" +
	"\x15RequestPaymentDetails\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x03R\tpaymentId\x12&\n" +
	"\x0ffrom_account_id\x18\x02 \x01(\x03R\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x03 \x01(\x03R\vtoAccountId\x12!\n" +
	"\fpayment_type\x18\x04 \x01(\tR\vpaymentType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12%\n" +
	"\x0epayment_method\x18\b \x01(\tR\rpaymentMethod\x12)\n" +
	"\x10reference_number\x18\t \x01(\tR\x0freferenceNumber\x12-\n" +
	"\x12external_reference\x18\n" +
	" \x01(\tR\x11externalReference\"\xf0\x02\n" +
	"\x13ReplyPaymentDetails\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x03R\tpaymentId\x12&\n" +
	"\x0ffrom_account_id\x18\x02 \x01(\x03R\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x03 \x01(\x03R\vtoAccountId\x12!\n" +
	"\fpayment_type\x18\x04 \x01(\tR\vpaymentType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12%\n" +
	"\x0epayment_method\x18\b \x01(\tR\rpaymentMethod\x12)\n" +
	"\x10reference_number\x18\t \x01(\tR\x0freferenceNumber\x12-\n" +
	"\x12external_reference\x18\n" +
	" \x01(\tR\x11externalReference2\x94\x02\n" +
	"\fNotification\x12z\n" +
	"\x12CreateNotification\x12\".helloworld.v1.RequestNotification\x1a .helloworld.v1.ReplyNotification\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/alert/notification\x12\x87\x01\n" +
	"\x13PaymentNotification\x12$.helloworld.v1.RequestPaymentDetails\x1a\".helloworld.v1.ReplyPaymentDetails\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/alert/notification/paymentBY\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z$message-service/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_greeter_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_greeter_proto_rawDescData []byte
)

func file_api_helloworld_v1_greeter_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_greeter_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_greeter_proto_rawDesc), len(file_api_helloworld_v1_greeter_proto_rawDesc)))
	})
	return file_api_helloworld_v1_greeter_proto_rawDescData
}

var file_api_helloworld_v1_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_helloworld_v1_greeter_proto_goTypes = []any{
	(*RequestNotification)(nil),   // 0: helloworld.v1.RequestNotification
	(*ReplyNotification)(nil),     // 1: helloworld.v1.ReplyNotification
	(*RequestPaymentDetails)(nil), // 2: helloworld.v1.RequestPaymentDetails
	(*ReplyPaymentDetails)(nil),   // 3: helloworld.v1.ReplyPaymentDetails
}
var file_api_helloworld_v1_greeter_proto_depIdxs = []int32{
	0, // 0: helloworld.v1.Notification.CreateNotification:input_type -> helloworld.v1.RequestNotification
	2, // 1: helloworld.v1.Notification.PaymentNotification:input_type -> helloworld.v1.RequestPaymentDetails
	1, // 2: helloworld.v1.Notification.CreateNotification:output_type -> helloworld.v1.ReplyNotification
	3, // 3: helloworld.v1.Notification.PaymentNotification:output_type -> helloworld.v1.ReplyPaymentDetails
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_greeter_proto_init() }
func file_api_helloworld_v1_greeter_proto_init() {
	if File_api_helloworld_v1_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_greeter_proto_rawDesc), len(file_api_helloworld_v1_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_greeter_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_greeter_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_greeter_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_greeter_proto = out.File
	file_api_helloworld_v1_greeter_proto_goTypes = nil
	file_api_helloworld_v1_greeter_proto_depIdxs = nil
}
