// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/helloworld/v1/greeter.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveAccBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int64                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveAccBlockRequest) Reset() {
	*x = SaveAccBlockRequest{}
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveAccBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAccBlockRequest) ProtoMessage() {}

func (x *SaveAccBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAccBlockRequest.ProtoReflect.Descriptor instead.
func (*SaveAccBlockRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *SaveAccBlockRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *SaveAccBlockRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SaveAccBlockRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SaveAccBlockRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SaveAccBlockReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int64                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveAccBlockReply) Reset() {
	*x = SaveAccBlockReply{}
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveAccBlockReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAccBlockReply) ProtoMessage() {}

func (x *SaveAccBlockReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAccBlockReply.ProtoReflect.Descriptor instead.
func (*SaveAccBlockReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *SaveAccBlockReply) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *SaveAccBlockReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SaveAccBlockReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SaveAccBlockReply) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SaveAccBlockReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetAccBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int64                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccBlockRequest) Reset() {
	*x = GetAccBlockRequest{}
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccBlockRequest) ProtoMessage() {}

func (x *GetAccBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccBlockRequest.ProtoReflect.Descriptor instead.
func (*GetAccBlockRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_greeter_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccBlockRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

type GetAccBlockReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int64                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccBlockReply) Reset() {
	*x = GetAccBlockReply{}
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccBlockReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccBlockReply) ProtoMessage() {}

func (x *GetAccBlockReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccBlockReply.ProtoReflect.Descriptor instead.
func (*GetAccBlockReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_greeter_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccBlockReply) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *GetAccBlockReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetAccBlockReply) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetAccBlockReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateAccBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int64                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccBlockRequest) Reset() {
	*x = UpdateAccBlockRequest{}
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccBlockRequest) ProtoMessage() {}

func (x *UpdateAccBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccBlockRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccBlockRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_greeter_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAccBlockRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *UpdateAccBlockRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateAccBlockRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *UpdateAccBlockRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateAccBlockReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int64                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccBlockReply) Reset() {
	*x = UpdateAccBlockReply{}
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccBlockReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccBlockReply) ProtoMessage() {}

func (x *UpdateAccBlockReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccBlockReply.ProtoReflect.Descriptor instead.
func (*UpdateAccBlockReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_greeter_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAccBlockReply) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *UpdateAccBlockReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateAccBlockReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateAccBlockReply) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *UpdateAccBlockReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_helloworld_v1_greeter_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_greeter_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/helloworld/v1/greeter.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"\x88\x01\n" +
	"\x13SaveAccBlockRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x03R\n" +
	"customerId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\xa0\x01\n" +
	"\x11SaveAccBlockReply\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x03R\n" +
	"customerId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"5\n" +
	"\x12GetAccBlockRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x03R\n" +
	"customerId\"\x85\x01\n" +
	"\x10GetAccBlockReply\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x03R\n" +
	"customerId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\x8a\x01\n" +
	"\x15UpdateAccBlockRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x03R\n" +
	"customerId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\xa2\x01\n" +
	"\x13UpdateAccBlockReply\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x03R\n" +
	"customerId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status2\x8c\x03\n" +
	"\x13AccountBlockService\x12q\n" +
	"\fSaveAccBlock\x12\".helloworld.v1.SaveAccBlockRequest\x1a .helloworld.v1.SaveAccBlockReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/SaveAccBlock\x12x\n" +
	"\vGetAccBlock\x12!.helloworld.v1.GetAccBlockRequest\x1a\x1f.helloworld.v1.GetAccBlockReply\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/GetAccBlock/{customer_id}\x12\x87\x01\n" +
	"\x0eUpdateAccBlock\x12$.helloworld.v1.UpdateAccBlockRequest\x1a\".helloworld.v1.UpdateAccBlockReply\"+\x82\xd3\xe4\x93\x02%:\x01*\x1a /v1/UpdateAccBlock/{customer_id}BV\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z!BlockAccount/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_greeter_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_greeter_proto_rawDescData []byte
)

func file_api_helloworld_v1_greeter_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_greeter_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_greeter_proto_rawDesc), len(file_api_helloworld_v1_greeter_proto_rawDesc)))
	})
	return file_api_helloworld_v1_greeter_proto_rawDescData
}

var file_api_helloworld_v1_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_helloworld_v1_greeter_proto_goTypes = []any{
	(*SaveAccBlockRequest)(nil),   // 0: helloworld.v1.SaveAccBlockRequest
	(*SaveAccBlockReply)(nil),     // 1: helloworld.v1.SaveAccBlockReply
	(*GetAccBlockRequest)(nil),    // 2: helloworld.v1.GetAccBlockRequest
	(*GetAccBlockReply)(nil),      // 3: helloworld.v1.GetAccBlockReply
	(*UpdateAccBlockRequest)(nil), // 4: helloworld.v1.UpdateAccBlockRequest
	(*UpdateAccBlockReply)(nil),   // 5: helloworld.v1.UpdateAccBlockReply
}
var file_api_helloworld_v1_greeter_proto_depIdxs = []int32{
	0, // 0: helloworld.v1.AccountBlockService.SaveAccBlock:input_type -> helloworld.v1.SaveAccBlockRequest
	2, // 1: helloworld.v1.AccountBlockService.GetAccBlock:input_type -> helloworld.v1.GetAccBlockRequest
	4, // 2: helloworld.v1.AccountBlockService.UpdateAccBlock:input_type -> helloworld.v1.UpdateAccBlockRequest
	1, // 3: helloworld.v1.AccountBlockService.SaveAccBlock:output_type -> helloworld.v1.SaveAccBlockReply
	3, // 4: helloworld.v1.AccountBlockService.GetAccBlock:output_type -> helloworld.v1.GetAccBlockReply
	5, // 5: helloworld.v1.AccountBlockService.UpdateAccBlock:output_type -> helloworld.v1.UpdateAccBlockReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_greeter_proto_init() }
func file_api_helloworld_v1_greeter_proto_init() {
	if File_api_helloworld_v1_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_greeter_proto_rawDesc), len(file_api_helloworld_v1_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_greeter_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_greeter_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_greeter_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_greeter_proto = out.File
	file_api_helloworld_v1_greeter_proto_goTypes = nil
	file_api_helloworld_v1_greeter_proto_depIdxs = nil
}
