// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/helloworld/v1/greeter.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CacheRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber    int64                  `protobuf:"varint,1,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AvailableBalance int64                  `protobuf:"varint,2,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CacheRequest) Reset() {
	*x = CacheRequest{}
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheRequest) ProtoMessage() {}

func (x *CacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheRequest.ProtoReflect.Descriptor instead.
func (*CacheRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *CacheRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *CacheRequest) GetAvailableBalance() int64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *CacheRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CacheResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber    int64                  `protobuf:"varint,3,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AvailableBalance int64                  `protobuf:"varint,2,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CacheResponse) Reset() {
	*x = CacheResponse{}
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheResponse) ProtoMessage() {}

func (x *CacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheResponse.ProtoReflect.Descriptor instead.
func (*CacheResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *CacheResponse) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *CacheResponse) GetAvailableBalance() int64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

var File_api_helloworld_v1_greeter_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_greeter_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/helloworld/v1/greeter.proto\x12\rhelloworld.v1\x1a\x1bgoogle/protobuf/empty.proto\"|\n" +
	"\fCacheRequest\x12$\n" +
	"\raccountNumber\x18\x01 \x01(\x03R\raccountNumber\x12*\n" +
	"\x10availableBalance\x18\x02 \x01(\x03R\x10availableBalance\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"a\n" +
	"\rCacheResponse\x12$\n" +
	"\raccountNumber\x18\x03 \x01(\x03R\raccountNumber\x12*\n" +
	"\x10availableBalance\x18\x02 \x01(\x03R\x10availableBalance2\xed\x01\n" +
	"\x13BalanceCacheService\x12I\n" +
	"\n" +
	"GetBalance\x12\x1b.helloworld.v1.CacheRequest\x1a\x1c.helloworld.v1.CacheResponse\"\x00\x12C\n" +
	"\n" +
	"SetBalance\x12\x1b.helloworld.v1.CacheRequest\x1a\x16.google.protobuf.Empty\"\x00\x12F\n" +
	"\rDeleteBalance\x12\x1b.helloworld.v1.CacheRequest\x1a\x16.google.protobuf.Empty\"\x00BD\n" +
	"\x1cdev.kratos.api.helloworld.v1P\x01Z\"cache_service/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_greeter_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_greeter_proto_rawDescData []byte
)

func file_api_helloworld_v1_greeter_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_greeter_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_greeter_proto_rawDesc), len(file_api_helloworld_v1_greeter_proto_rawDesc)))
	})
	return file_api_helloworld_v1_greeter_proto_rawDescData
}

var file_api_helloworld_v1_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_helloworld_v1_greeter_proto_goTypes = []any{
	(*CacheRequest)(nil),  // 0: helloworld.v1.CacheRequest
	(*CacheResponse)(nil), // 1: helloworld.v1.CacheResponse
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_api_helloworld_v1_greeter_proto_depIdxs = []int32{
	0, // 0: helloworld.v1.BalanceCacheService.GetBalance:input_type -> helloworld.v1.CacheRequest
	0, // 1: helloworld.v1.BalanceCacheService.SetBalance:input_type -> helloworld.v1.CacheRequest
	0, // 2: helloworld.v1.BalanceCacheService.DeleteBalance:input_type -> helloworld.v1.CacheRequest
	1, // 3: helloworld.v1.BalanceCacheService.GetBalance:output_type -> helloworld.v1.CacheResponse
	2, // 4: helloworld.v1.BalanceCacheService.SetBalance:output_type -> google.protobuf.Empty
	2, // 5: helloworld.v1.BalanceCacheService.DeleteBalance:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_greeter_proto_init() }
func file_api_helloworld_v1_greeter_proto_init() {
	if File_api_helloworld_v1_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_greeter_proto_rawDesc), len(file_api_helloworld_v1_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_greeter_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_greeter_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_greeter_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_greeter_proto = out.File
	file_api_helloworld_v1_greeter_proto_goTypes = nil
	file_api_helloworld_v1_greeter_proto_depIdxs = nil
}
