// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"payment/internal/biz"
	"payment/internal/client"
	"payment/internal/conf"
	"payment/internal/data"
	"payment/internal/server"
	"payment/internal/service"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"

	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	accountClient:=client.AccountClient()
	customerClient:=client.CustomerClient()
	transactionClient:=client.TransactionnClient()
	
	greeterRepo := data.NewPaymentRepo(dataData, logger)
	greeterUsecase := biz.NewPaymentUsecase(greeterRepo, logger)
	greeterService := service.NewPaymentService(greeterUsecase,accountClient,customerClient,transactionClient)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
