// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/helloworld/v1/rel_cus_acc.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Create Relationship Request
type CreateRelationRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CustomerId        int64                  `protobuf:"varint,1,opt,name=customerId,proto3" json:"customerId,omitempty"`
	CustomerNumber    string                 `protobuf:"bytes,2,opt,name=customerNumber,proto3" json:"customerNumber,omitempty"`
	FirstName         string                 `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName          string                 `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email             string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone             string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	DateOfBirth       string                 `protobuf:"bytes,7,opt,name=dateOfBirth,proto3" json:"dateOfBirth,omitempty"`
	CustomerStatus    string                 `protobuf:"bytes,8,opt,name=customerStatus,proto3" json:"customerStatus,omitempty"`
	KycStatus         string                 `protobuf:"bytes,9,opt,name=kycStatus,proto3" json:"kycStatus,omitempty"`
	CustomerCreatedAt string                 `protobuf:"bytes,10,opt,name=customerCreatedAt,proto3" json:"customerCreatedAt,omitempty"`
	CustomerUpdatedAt string                 `protobuf:"bytes,11,opt,name=customerUpdatedAt,proto3" json:"customerUpdatedAt,omitempty"`
	AccountId         int64                  `protobuf:"varint,12,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber     string                 `protobuf:"bytes,13,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType       string                 `protobuf:"bytes,14,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Currency          string                 `protobuf:"bytes,15,opt,name=currency,proto3" json:"currency,omitempty"`
	AccountStatus     string                 `protobuf:"bytes,16,opt,name=accountStatus,proto3" json:"accountStatus,omitempty"`
	AvailableBalance  int64                  `protobuf:"varint,17,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	PendingBalance    int64                  `protobuf:"varint,18,opt,name=pendingBalance,proto3" json:"pendingBalance,omitempty"`
	CreditLimit       string                 `protobuf:"bytes,19,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	LastTransactionAt string                 `protobuf:"bytes,20,opt,name=lastTransactionAt,proto3" json:"lastTransactionAt,omitempty"`
	AccountCreatedAt  string                 `protobuf:"bytes,21,opt,name=accountCreatedAt,proto3" json:"accountCreatedAt,omitempty"`
	LastUsedAt        string                 `protobuf:"bytes,22,opt,name=lastUsedAt,proto3" json:"lastUsedAt,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateRelationRequest) Reset() {
	*x = CreateRelationRequest{}
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRelationRequest) ProtoMessage() {}

func (x *CreateRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRelationRequest.ProtoReflect.Descriptor instead.
func (*CreateRelationRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_rel_cus_acc_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRelationRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *CreateRelationRequest) GetCustomerNumber() string {
	if x != nil {
		return x.CustomerNumber
	}
	return ""
}

func (x *CreateRelationRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateRelationRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateRelationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateRelationRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateRelationRequest) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *CreateRelationRequest) GetCustomerStatus() string {
	if x != nil {
		return x.CustomerStatus
	}
	return ""
}

func (x *CreateRelationRequest) GetKycStatus() string {
	if x != nil {
		return x.KycStatus
	}
	return ""
}

func (x *CreateRelationRequest) GetCustomerCreatedAt() string {
	if x != nil {
		return x.CustomerCreatedAt
	}
	return ""
}

func (x *CreateRelationRequest) GetCustomerUpdatedAt() string {
	if x != nil {
		return x.CustomerUpdatedAt
	}
	return ""
}

func (x *CreateRelationRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateRelationRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *CreateRelationRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *CreateRelationRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateRelationRequest) GetAccountStatus() string {
	if x != nil {
		return x.AccountStatus
	}
	return ""
}

func (x *CreateRelationRequest) GetAvailableBalance() int64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *CreateRelationRequest) GetPendingBalance() int64 {
	if x != nil {
		return x.PendingBalance
	}
	return 0
}

func (x *CreateRelationRequest) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *CreateRelationRequest) GetLastTransactionAt() string {
	if x != nil {
		return x.LastTransactionAt
	}
	return ""
}

func (x *CreateRelationRequest) GetAccountCreatedAt() string {
	if x != nil {
		return x.AccountCreatedAt
	}
	return ""
}

func (x *CreateRelationRequest) GetLastUsedAt() string {
	if x != nil {
		return x.LastUsedAt
	}
	return ""
}

// Relationship Response
type RelationReply struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId        int64                  `protobuf:"varint,2,opt,name=customerId,proto3" json:"customerId,omitempty"`
	CustomerNumber    string                 `protobuf:"bytes,3,opt,name=customerNumber,proto3" json:"customerNumber,omitempty"`
	FirstName         string                 `protobuf:"bytes,4,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName          string                 `protobuf:"bytes,5,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email             string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phone             string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	DateOfBirth       string                 `protobuf:"bytes,8,opt,name=dateOfBirth,proto3" json:"dateOfBirth,omitempty"`
	CustomerStatus    string                 `protobuf:"bytes,9,opt,name=customerStatus,proto3" json:"customerStatus,omitempty"`
	KycStatus         string                 `protobuf:"bytes,10,opt,name=kycStatus,proto3" json:"kycStatus,omitempty"`
	CustomerCreatedAt string                 `protobuf:"bytes,11,opt,name=customerCreatedAt,proto3" json:"customerCreatedAt,omitempty"`
	CustomerUpdatedAt string                 `protobuf:"bytes,12,opt,name=customerUpdatedAt,proto3" json:"customerUpdatedAt,omitempty"`
	AccountId         int64                  `protobuf:"varint,13,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber     string                 `protobuf:"bytes,14,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType       string                 `protobuf:"bytes,15,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Currency          string                 `protobuf:"bytes,16,opt,name=currency,proto3" json:"currency,omitempty"`
	AccountStatus     string                 `protobuf:"bytes,17,opt,name=accountStatus,proto3" json:"accountStatus,omitempty"`
	AvailableBalance  int64                  `protobuf:"varint,18,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	PendingBalance    int64                  `protobuf:"varint,19,opt,name=pendingBalance,proto3" json:"pendingBalance,omitempty"`
	CreditLimit       string                 `protobuf:"bytes,20,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	LastTransactionAt string                 `protobuf:"bytes,21,opt,name=lastTransactionAt,proto3" json:"lastTransactionAt,omitempty"`
	AccountCreatedAt  string                 `protobuf:"bytes,22,opt,name=accountCreatedAt,proto3" json:"accountCreatedAt,omitempty"`
	LastUsedAt        string                 `protobuf:"bytes,23,opt,name=lastUsedAt,proto3" json:"lastUsedAt,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RelationReply) Reset() {
	*x = RelationReply{}
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationReply) ProtoMessage() {}

func (x *RelationReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationReply.ProtoReflect.Descriptor instead.
func (*RelationReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_rel_cus_acc_proto_rawDescGZIP(), []int{1}
}

func (x *RelationReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RelationReply) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *RelationReply) GetCustomerNumber() string {
	if x != nil {
		return x.CustomerNumber
	}
	return ""
}

func (x *RelationReply) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RelationReply) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RelationReply) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RelationReply) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RelationReply) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *RelationReply) GetCustomerStatus() string {
	if x != nil {
		return x.CustomerStatus
	}
	return ""
}

func (x *RelationReply) GetKycStatus() string {
	if x != nil {
		return x.KycStatus
	}
	return ""
}

func (x *RelationReply) GetCustomerCreatedAt() string {
	if x != nil {
		return x.CustomerCreatedAt
	}
	return ""
}

func (x *RelationReply) GetCustomerUpdatedAt() string {
	if x != nil {
		return x.CustomerUpdatedAt
	}
	return ""
}

func (x *RelationReply) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *RelationReply) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *RelationReply) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *RelationReply) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RelationReply) GetAccountStatus() string {
	if x != nil {
		return x.AccountStatus
	}
	return ""
}

func (x *RelationReply) GetAvailableBalance() int64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *RelationReply) GetPendingBalance() int64 {
	if x != nil {
		return x.PendingBalance
	}
	return 0
}

func (x *RelationReply) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *RelationReply) GetLastTransactionAt() string {
	if x != nil {
		return x.LastTransactionAt
	}
	return ""
}

func (x *RelationReply) GetAccountCreatedAt() string {
	if x != nil {
		return x.AccountCreatedAt
	}
	return ""
}

func (x *RelationReply) GetLastUsedAt() string {
	if x != nil {
		return x.LastUsedAt
	}
	return ""
}

// Create Relationship Response
type CreateRelationReply struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId        int64                  `protobuf:"varint,2,opt,name=customerId,proto3" json:"customerId,omitempty"`
	CustomerNumber    string                 `protobuf:"bytes,3,opt,name=customerNumber,proto3" json:"customerNumber,omitempty"`
	FirstName         string                 `protobuf:"bytes,4,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName          string                 `protobuf:"bytes,5,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email             string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phone             string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	DateOfBirth       string                 `protobuf:"bytes,8,opt,name=dateOfBirth,proto3" json:"dateOfBirth,omitempty"`
	CustomerStatus    string                 `protobuf:"bytes,9,opt,name=customerStatus,proto3" json:"customerStatus,omitempty"`
	KycStatus         string                 `protobuf:"bytes,10,opt,name=kycStatus,proto3" json:"kycStatus,omitempty"`
	CustomerCreatedAt string                 `protobuf:"bytes,11,opt,name=customerCreatedAt,proto3" json:"customerCreatedAt,omitempty"`
	CustomerUpdatedAt string                 `protobuf:"bytes,12,opt,name=customerUpdatedAt,proto3" json:"customerUpdatedAt,omitempty"`
	AccountId         int64                  `protobuf:"varint,13,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber     string                 `protobuf:"bytes,14,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType       string                 `protobuf:"bytes,15,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Currency          string                 `protobuf:"bytes,16,opt,name=currency,proto3" json:"currency,omitempty"`
	AccountStatus     string                 `protobuf:"bytes,17,opt,name=accountStatus,proto3" json:"accountStatus,omitempty"`
	AvailableBalance  int64                  `protobuf:"varint,18,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	PendingBalance    int64                  `protobuf:"varint,19,opt,name=pendingBalance,proto3" json:"pendingBalance,omitempty"`
	CreditLimit       string                 `protobuf:"bytes,20,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	LastTransactionAt string                 `protobuf:"bytes,21,opt,name=lastTransactionAt,proto3" json:"lastTransactionAt,omitempty"`
	AccountCreatedAt  string                 `protobuf:"bytes,22,opt,name=accountCreatedAt,proto3" json:"accountCreatedAt,omitempty"`
	LastUsedAt        string                 `protobuf:"bytes,23,opt,name=lastUsedAt,proto3" json:"lastUsedAt,omitempty"`
	Message           string                 `protobuf:"bytes,24,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateRelationReply) Reset() {
	*x = CreateRelationReply{}
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRelationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRelationReply) ProtoMessage() {}

func (x *CreateRelationReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRelationReply.ProtoReflect.Descriptor instead.
func (*CreateRelationReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_rel_cus_acc_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRelationReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateRelationReply) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *CreateRelationReply) GetCustomerNumber() string {
	if x != nil {
		return x.CustomerNumber
	}
	return ""
}

func (x *CreateRelationReply) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateRelationReply) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateRelationReply) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateRelationReply) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateRelationReply) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *CreateRelationReply) GetCustomerStatus() string {
	if x != nil {
		return x.CustomerStatus
	}
	return ""
}

func (x *CreateRelationReply) GetKycStatus() string {
	if x != nil {
		return x.KycStatus
	}
	return ""
}

func (x *CreateRelationReply) GetCustomerCreatedAt() string {
	if x != nil {
		return x.CustomerCreatedAt
	}
	return ""
}

func (x *CreateRelationReply) GetCustomerUpdatedAt() string {
	if x != nil {
		return x.CustomerUpdatedAt
	}
	return ""
}

func (x *CreateRelationReply) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateRelationReply) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *CreateRelationReply) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *CreateRelationReply) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateRelationReply) GetAccountStatus() string {
	if x != nil {
		return x.AccountStatus
	}
	return ""
}

func (x *CreateRelationReply) GetAvailableBalance() int64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *CreateRelationReply) GetPendingBalance() int64 {
	if x != nil {
		return x.PendingBalance
	}
	return 0
}

func (x *CreateRelationReply) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *CreateRelationReply) GetLastTransactionAt() string {
	if x != nil {
		return x.LastTransactionAt
	}
	return ""
}

func (x *CreateRelationReply) GetAccountCreatedAt() string {
	if x != nil {
		return x.AccountCreatedAt
	}
	return ""
}

func (x *CreateRelationReply) GetLastUsedAt() string {
	if x != nil {
		return x.LastUsedAt
	}
	return ""
}

func (x *CreateRelationReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Update Relationship Request
type UpdateRelationRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId        int64                  `protobuf:"varint,2,opt,name=customerId,proto3" json:"customerId,omitempty"`
	CustomerNumber    string                 `protobuf:"bytes,3,opt,name=customerNumber,proto3" json:"customerNumber,omitempty"`
	FirstName         string                 `protobuf:"bytes,4,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName          string                 `protobuf:"bytes,5,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email             string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phone             string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	DateOfBirth       string                 `protobuf:"bytes,8,opt,name=dateOfBirth,proto3" json:"dateOfBirth,omitempty"`
	CustomerStatus    string                 `protobuf:"bytes,9,opt,name=customerStatus,proto3" json:"customerStatus,omitempty"`
	KycStatus         string                 `protobuf:"bytes,10,opt,name=kycStatus,proto3" json:"kycStatus,omitempty"`
	CustomerUpdatedAt string                 `protobuf:"bytes,11,opt,name=customerUpdatedAt,proto3" json:"customerUpdatedAt,omitempty"`
	AccountId         int64                  `protobuf:"varint,12,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber     string                 `protobuf:"bytes,13,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType       string                 `protobuf:"bytes,14,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Currency          string                 `protobuf:"bytes,15,opt,name=currency,proto3" json:"currency,omitempty"`
	AccountStatus     string                 `protobuf:"bytes,16,opt,name=accountStatus,proto3" json:"accountStatus,omitempty"`
	AvailableBalance  int64                  `protobuf:"varint,17,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	PendingBalance    int64                  `protobuf:"varint,18,opt,name=pendingBalance,proto3" json:"pendingBalance,omitempty"`
	CreditLimit       string                 `protobuf:"bytes,19,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	LastTransactionAt string                 `protobuf:"bytes,20,opt,name=lastTransactionAt,proto3" json:"lastTransactionAt,omitempty"`
	LastUsedAt        string                 `protobuf:"bytes,21,opt,name=lastUsedAt,proto3" json:"lastUsedAt,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateRelationRequest) Reset() {
	*x = UpdateRelationRequest{}
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRelationRequest) ProtoMessage() {}

func (x *UpdateRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRelationRequest.ProtoReflect.Descriptor instead.
func (*UpdateRelationRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_rel_cus_acc_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRelationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRelationRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *UpdateRelationRequest) GetCustomerNumber() string {
	if x != nil {
		return x.CustomerNumber
	}
	return ""
}

func (x *UpdateRelationRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateRelationRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateRelationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateRelationRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateRelationRequest) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *UpdateRelationRequest) GetCustomerStatus() string {
	if x != nil {
		return x.CustomerStatus
	}
	return ""
}

func (x *UpdateRelationRequest) GetKycStatus() string {
	if x != nil {
		return x.KycStatus
	}
	return ""
}

func (x *UpdateRelationRequest) GetCustomerUpdatedAt() string {
	if x != nil {
		return x.CustomerUpdatedAt
	}
	return ""
}

func (x *UpdateRelationRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateRelationRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *UpdateRelationRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *UpdateRelationRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateRelationRequest) GetAccountStatus() string {
	if x != nil {
		return x.AccountStatus
	}
	return ""
}

func (x *UpdateRelationRequest) GetAvailableBalance() int64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *UpdateRelationRequest) GetPendingBalance() int64 {
	if x != nil {
		return x.PendingBalance
	}
	return 0
}

func (x *UpdateRelationRequest) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *UpdateRelationRequest) GetLastTransactionAt() string {
	if x != nil {
		return x.LastTransactionAt
	}
	return ""
}

func (x *UpdateRelationRequest) GetLastUsedAt() string {
	if x != nil {
		return x.LastUsedAt
	}
	return ""
}

// Update Relationship Response
type UpdateRelationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Relations     []*RelationReply       `protobuf:"bytes,2,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRelationReply) Reset() {
	*x = UpdateRelationReply{}
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRelationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRelationReply) ProtoMessage() {}

func (x *UpdateRelationReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRelationReply.ProtoReflect.Descriptor instead.
func (*UpdateRelationReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_rel_cus_acc_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRelationReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateRelationReply) GetRelations() []*RelationReply {
	if x != nil {
		return x.Relations
	}
	return nil
}

// Delete Relationship Request
type DeleteRelationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRelationRequest) Reset() {
	*x = DeleteRelationRequest{}
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRelationRequest) ProtoMessage() {}

func (x *DeleteRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRelationRequest.ProtoReflect.Descriptor instead.
func (*DeleteRelationRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_rel_cus_acc_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRelationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Delete Relationship Response
type DeleteRelationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRelationReply) Reset() {
	*x = DeleteRelationReply{}
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRelationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRelationReply) ProtoMessage() {}

func (x *DeleteRelationReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRelationReply.ProtoReflect.Descriptor instead.
func (*DeleteRelationReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_rel_cus_acc_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRelationReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Get relationships by customer ID
type GetRelationsByCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int64                  `protobuf:"varint,1,opt,name=customerId,proto3" json:"customerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationsByCustomerRequest) Reset() {
	*x = GetRelationsByCustomerRequest{}
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationsByCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationsByCustomerRequest) ProtoMessage() {}

func (x *GetRelationsByCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationsByCustomerRequest.ProtoReflect.Descriptor instead.
func (*GetRelationsByCustomerRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_rel_cus_acc_proto_rawDescGZIP(), []int{7}
}

func (x *GetRelationsByCustomerRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

type GetRelationsByCustomerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relations     []*RelationReply       `protobuf:"bytes,1,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationsByCustomerReply) Reset() {
	*x = GetRelationsByCustomerReply{}
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationsByCustomerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationsByCustomerReply) ProtoMessage() {}

func (x *GetRelationsByCustomerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationsByCustomerReply.ProtoReflect.Descriptor instead.
func (*GetRelationsByCustomerReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_rel_cus_acc_proto_rawDescGZIP(), []int{8}
}

func (x *GetRelationsByCustomerReply) GetRelations() []*RelationReply {
	if x != nil {
		return x.Relations
	}
	return nil
}

// Get relationship by account ID
type GetRelationByAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationByAccountRequest) Reset() {
	*x = GetRelationByAccountRequest{}
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationByAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationByAccountRequest) ProtoMessage() {}

func (x *GetRelationByAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationByAccountRequest.ProtoReflect.Descriptor instead.
func (*GetRelationByAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_rel_cus_acc_proto_rawDescGZIP(), []int{9}
}

func (x *GetRelationByAccountRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type GetRelationByAccountReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relation      *RelationReply         `protobuf:"bytes,1,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationByAccountReply) Reset() {
	*x = GetRelationByAccountReply{}
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationByAccountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationByAccountReply) ProtoMessage() {}

func (x *GetRelationByAccountReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationByAccountReply.ProtoReflect.Descriptor instead.
func (*GetRelationByAccountReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_rel_cus_acc_proto_rawDescGZIP(), []int{10}
}

func (x *GetRelationByAccountReply) GetRelation() *RelationReply {
	if x != nil {
		return x.Relation
	}
	return nil
}

// Get relationship by relation ID
type GetRelationByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationByIdRequest) Reset() {
	*x = GetRelationByIdRequest{}
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationByIdRequest) ProtoMessage() {}

func (x *GetRelationByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationByIdRequest.ProtoReflect.Descriptor instead.
func (*GetRelationByIdRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_rel_cus_acc_proto_rawDescGZIP(), []int{11}
}

func (x *GetRelationByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRelationByIdReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relation      *RelationReply         `protobuf:"bytes,1,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationByIdReply) Reset() {
	*x = GetRelationByIdReply{}
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationByIdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationByIdReply) ProtoMessage() {}

func (x *GetRelationByIdReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationByIdReply.ProtoReflect.Descriptor instead.
func (*GetRelationByIdReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_rel_cus_acc_proto_rawDescGZIP(), []int{12}
}

func (x *GetRelationByIdReply) GetRelation() *RelationReply {
	if x != nil {
		return x.Relation
	}
	return nil
}

// Get all relationships
type GetAllRelationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional pagination parameters
	Page          int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRelationsRequest) Reset() {
	*x = GetAllRelationsRequest{}
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRelationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRelationsRequest) ProtoMessage() {}

func (x *GetAllRelationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRelationsRequest.ProtoReflect.Descriptor instead.
func (*GetAllRelationsRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_rel_cus_acc_proto_rawDescGZIP(), []int{13}
}

func (x *GetAllRelationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllRelationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetAllRelationsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relations     []*RelationReply       `protobuf:"bytes,1,rep,name=relations,proto3" json:"relations,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=currentPage,proto3" json:"currentPage,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=totalPages,proto3" json:"totalPages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRelationsReply) Reset() {
	*x = GetAllRelationsReply{}
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRelationsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRelationsReply) ProtoMessage() {}

func (x *GetAllRelationsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_rel_cus_acc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRelationsReply.ProtoReflect.Descriptor instead.
func (*GetAllRelationsReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_rel_cus_acc_proto_rawDescGZIP(), []int{14}
}

func (x *GetAllRelationsReply) GetRelations() []*RelationReply {
	if x != nil {
		return x.Relations
	}
	return nil
}

func (x *GetAllRelationsReply) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetAllRelationsReply) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetAllRelationsReply) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_api_helloworld_v1_rel_cus_acc_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_rel_cus_acc_proto_rawDesc = "" +
	"\n" +
	"#api/helloworld/v1/rel_cus_acc.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"\xa1\x06\n" +
	"\x15CreateRelationRequest\x12\x1e\n" +
	"\n" +
	"customerId\x18\x01 \x01(\x03R\n" +
	"customerId\x12&\n" +
	"\x0ecustomerNumber\x18\x02 \x01(\tR\x0ecustomerNumber\x12\x1c\n" +
	"\tfirstName\x18\x03 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x04 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12 \n" +
	"\vdateOfBirth\x18\a \x01(\tR\vdateOfBirth\x12&\n" +
	"\x0ecustomerStatus\x18\b \x01(\tR\x0ecustomerStatus\x12\x1c\n" +
	"\tkycStatus\x18\t \x01(\tR\tkycStatus\x12,\n" +
	"\x11customerCreatedAt\x18\n" +
	" \x01(\tR\x11customerCreatedAt\x12,\n" +
	"\x11customerUpdatedAt\x18\v \x01(\tR\x11customerUpdatedAt\x12\x1c\n" +
	"\taccountId\x18\f \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\r \x01(\tR\raccountNumber\x12 \n" +
	"\vaccountType\x18\x0e \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x0f \x01(\tR\bcurrency\x12$\n" +
	"\raccountStatus\x18\x10 \x01(\tR\raccountStatus\x12*\n" +
	"\x10availableBalance\x18\x11 \x01(\x03R\x10availableBalance\x12&\n" +
	"\x0ependingBalance\x18\x12 \x01(\x03R\x0ependingBalance\x12 \n" +
	"\vcreditLimit\x18\x13 \x01(\tR\vcreditLimit\x12,\n" +
	"\x11lastTransactionAt\x18\x14 \x01(\tR\x11lastTransactionAt\x12*\n" +
	"\x10accountCreatedAt\x18\x15 \x01(\tR\x10accountCreatedAt\x12\x1e\n" +
	"\n" +
	"lastUsedAt\x18\x16 \x01(\tR\n" +
	"lastUsedAt\"\xa9\x06\n" +
	"\rRelationReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1e\n" +
	"\n" +
	"customerId\x18\x02 \x01(\x03R\n" +
	"customerId\x12&\n" +
	"\x0ecustomerNumber\x18\x03 \x01(\tR\x0ecustomerNumber\x12\x1c\n" +
	"\tfirstName\x18\x04 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x05 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12 \n" +
	"\vdateOfBirth\x18\b \x01(\tR\vdateOfBirth\x12&\n" +
	"\x0ecustomerStatus\x18\t \x01(\tR\x0ecustomerStatus\x12\x1c\n" +
	"\tkycStatus\x18\n" +
	" \x01(\tR\tkycStatus\x12,\n" +
	"\x11customerCreatedAt\x18\v \x01(\tR\x11customerCreatedAt\x12,\n" +
	"\x11customerUpdatedAt\x18\f \x01(\tR\x11customerUpdatedAt\x12\x1c\n" +
	"\taccountId\x18\r \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\x0e \x01(\tR\raccountNumber\x12 \n" +
	"\vaccountType\x18\x0f \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x10 \x01(\tR\bcurrency\x12$\n" +
	"\raccountStatus\x18\x11 \x01(\tR\raccountStatus\x12*\n" +
	"\x10availableBalance\x18\x12 \x01(\x03R\x10availableBalance\x12&\n" +
	"\x0ependingBalance\x18\x13 \x01(\x03R\x0ependingBalance\x12 \n" +
	"\vcreditLimit\x18\x14 \x01(\tR\vcreditLimit\x12,\n" +
	"\x11lastTransactionAt\x18\x15 \x01(\tR\x11lastTransactionAt\x12*\n" +
	"\x10accountCreatedAt\x18\x16 \x01(\tR\x10accountCreatedAt\x12\x1e\n" +
	"\n" +
	"lastUsedAt\x18\x17 \x01(\tR\n" +
	"lastUsedAt\"\xc9\x06\n" +
	"\x13CreateRelationReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1e\n" +
	"\n" +
	"customerId\x18\x02 \x01(\x03R\n" +
	"customerId\x12&\n" +
	"\x0ecustomerNumber\x18\x03 \x01(\tR\x0ecustomerNumber\x12\x1c\n" +
	"\tfirstName\x18\x04 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x05 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12 \n" +
	"\vdateOfBirth\x18\b \x01(\tR\vdateOfBirth\x12&\n" +
	"\x0ecustomerStatus\x18\t \x01(\tR\x0ecustomerStatus\x12\x1c\n" +
	"\tkycStatus\x18\n" +
	" \x01(\tR\tkycStatus\x12,\n" +
	"\x11customerCreatedAt\x18\v \x01(\tR\x11customerCreatedAt\x12,\n" +
	"\x11customerUpdatedAt\x18\f \x01(\tR\x11customerUpdatedAt\x12\x1c\n" +
	"\taccountId\x18\r \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\x0e \x01(\tR\raccountNumber\x12 \n" +
	"\vaccountType\x18\x0f \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x10 \x01(\tR\bcurrency\x12$\n" +
	"\raccountStatus\x18\x11 \x01(\tR\raccountStatus\x12*\n" +
	"\x10availableBalance\x18\x12 \x01(\x03R\x10availableBalance\x12&\n" +
	"\x0ependingBalance\x18\x13 \x01(\x03R\x0ependingBalance\x12 \n" +
	"\vcreditLimit\x18\x14 \x01(\tR\vcreditLimit\x12,\n" +
	"\x11lastTransactionAt\x18\x15 \x01(\tR\x11lastTransactionAt\x12*\n" +
	"\x10accountCreatedAt\x18\x16 \x01(\tR\x10accountCreatedAt\x12\x1e\n" +
	"\n" +
	"lastUsedAt\x18\x17 \x01(\tR\n" +
	"lastUsedAt\x12\x18\n" +
	"\amessage\x18\x18 \x01(\tR\amessage\"\xd7\x05\n" +
	"\x15UpdateRelationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1e\n" +
	"\n" +
	"customerId\x18\x02 \x01(\x03R\n" +
	"customerId\x12&\n" +
	"\x0ecustomerNumber\x18\x03 \x01(\tR\x0ecustomerNumber\x12\x1c\n" +
	"\tfirstName\x18\x04 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x05 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12 \n" +
	"\vdateOfBirth\x18\b \x01(\tR\vdateOfBirth\x12&\n" +
	"\x0ecustomerStatus\x18\t \x01(\tR\x0ecustomerStatus\x12\x1c\n" +
	"\tkycStatus\x18\n" +
	" \x01(\tR\tkycStatus\x12,\n" +
	"\x11customerUpdatedAt\x18\v \x01(\tR\x11customerUpdatedAt\x12\x1c\n" +
	"\taccountId\x18\f \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\r \x01(\tR\raccountNumber\x12 \n" +
	"\vaccountType\x18\x0e \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x0f \x01(\tR\bcurrency\x12$\n" +
	"\raccountStatus\x18\x10 \x01(\tR\raccountStatus\x12*\n" +
	"\x10availableBalance\x18\x11 \x01(\x03R\x10availableBalance\x12&\n" +
	"\x0ependingBalance\x18\x12 \x01(\x03R\x0ependingBalance\x12 \n" +
	"\vcreditLimit\x18\x13 \x01(\tR\vcreditLimit\x12,\n" +
	"\x11lastTransactionAt\x18\x14 \x01(\tR\x11lastTransactionAt\x12\x1e\n" +
	"\n" +
	"lastUsedAt\x18\x15 \x01(\tR\n" +
	"lastUsedAt\"k\n" +
	"\x13UpdateRelationReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12:\n" +
	"\trelations\x18\x02 \x03(\v2\x1c.helloworld.v1.RelationReplyR\trelations\"'\n" +
	"\x15DeleteRelationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"/\n" +
	"\x13DeleteRelationReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"?\n" +
	"\x1dGetRelationsByCustomerRequest\x12\x1e\n" +
	"\n" +
	"customerId\x18\x01 \x01(\x03R\n" +
	"customerId\"Y\n" +
	"\x1bGetRelationsByCustomerReply\x12:\n" +
	"\trelations\x18\x01 \x03(\v2\x1c.helloworld.v1.RelationReplyR\trelations\";\n" +
	"\x1bGetRelationByAccountRequest\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\"U\n" +
	"\x19GetRelationByAccountReply\x128\n" +
	"\brelation\x18\x01 \x01(\v2\x1c.helloworld.v1.RelationReplyR\brelation\"(\n" +
	"\x16GetRelationByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"P\n" +
	"\x14GetRelationByIdReply\x128\n" +
	"\brelation\x18\x01 \x01(\v2\x1c.helloworld.v1.RelationReplyR\brelation\"H\n" +
	"\x16GetAllRelationsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\"\xb4\x01\n" +
	"\x14GetAllRelationsReply\x12:\n" +
	"\trelations\x18\x01 \x03(\v2\x1c.helloworld.v1.RelationReplyR\trelations\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x02 \x01(\x05R\n" +
	"totalCount\x12 \n" +
	"\vcurrentPage\x18\x03 \x01(\x05R\vcurrentPage\x12\x1e\n" +
	"\n" +
	"totalPages\x18\x04 \x01(\x05R\n" +
	"totalPages2\xb2\x06\n" +
	"\tRelCusAcc\x12v\n" +
	"\x0eCreateRelation\x12$.helloworld.v1.CreateRelationRequest\x1a\".helloworld.v1.CreateRelationReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/rel-cus-acc\x12{\n" +
	"\x0eUpdateRelation\x12$.helloworld.v1.UpdateRelationRequest\x1a\".helloworld.v1.UpdateRelationReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*2\x14/v1/rel-cus-acc/{id}\x12x\n" +
	"\x0eDeleteRelation\x12$.helloworld.v1.DeleteRelationRequest\x1a\".helloworld.v1.DeleteRelationReply\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/v1/rel-cus-acc/{id}\x12\xa1\x01\n" +
	"\x16GetRelationsByCustomer\x12,.helloworld.v1.GetRelationsByCustomerRequest\x1a*.helloworld.v1.GetRelationsByCustomerReply\"-\x82\xd3\xe4\x93\x02'\x12%/v1/rel-cus-acc/customer/{customerId}\x12\x99\x01\n" +
	"\x14GetRelationByAccount\x12*.helloworld.v1.GetRelationByAccountRequest\x1a(.helloworld.v1.GetRelationByAccountReply\"+\x82\xd3\xe4\x93\x02%\x12#/v1/rel-cus-acc/account/{accountId}\x12v\n" +
	"\x0fGetAllRelations\x12%.helloworld.v1.GetAllRelationsRequest\x1a#.helloworld.v1.GetAllRelationsReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/rel-cus-accBR\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x10RelCusAccProtoV1P\x01Z\x1erelcusacc/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_rel_cus_acc_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_rel_cus_acc_proto_rawDescData []byte
)

func file_api_helloworld_v1_rel_cus_acc_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_rel_cus_acc_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_rel_cus_acc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_rel_cus_acc_proto_rawDesc), len(file_api_helloworld_v1_rel_cus_acc_proto_rawDesc)))
	})
	return file_api_helloworld_v1_rel_cus_acc_proto_rawDescData
}

var file_api_helloworld_v1_rel_cus_acc_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_helloworld_v1_rel_cus_acc_proto_goTypes = []any{
	(*CreateRelationRequest)(nil),         // 0: helloworld.v1.CreateRelationRequest
	(*RelationReply)(nil),                 // 1: helloworld.v1.RelationReply
	(*CreateRelationReply)(nil),           // 2: helloworld.v1.CreateRelationReply
	(*UpdateRelationRequest)(nil),         // 3: helloworld.v1.UpdateRelationRequest
	(*UpdateRelationReply)(nil),           // 4: helloworld.v1.UpdateRelationReply
	(*DeleteRelationRequest)(nil),         // 5: helloworld.v1.DeleteRelationRequest
	(*DeleteRelationReply)(nil),           // 6: helloworld.v1.DeleteRelationReply
	(*GetRelationsByCustomerRequest)(nil), // 7: helloworld.v1.GetRelationsByCustomerRequest
	(*GetRelationsByCustomerReply)(nil),   // 8: helloworld.v1.GetRelationsByCustomerReply
	(*GetRelationByAccountRequest)(nil),   // 9: helloworld.v1.GetRelationByAccountRequest
	(*GetRelationByAccountReply)(nil),     // 10: helloworld.v1.GetRelationByAccountReply
	(*GetRelationByIdRequest)(nil),        // 11: helloworld.v1.GetRelationByIdRequest
	(*GetRelationByIdReply)(nil),          // 12: helloworld.v1.GetRelationByIdReply
	(*GetAllRelationsRequest)(nil),        // 13: helloworld.v1.GetAllRelationsRequest
	(*GetAllRelationsReply)(nil),          // 14: helloworld.v1.GetAllRelationsReply
}
var file_api_helloworld_v1_rel_cus_acc_proto_depIdxs = []int32{
	1,  // 0: helloworld.v1.UpdateRelationReply.relations:type_name -> helloworld.v1.RelationReply
	1,  // 1: helloworld.v1.GetRelationsByCustomerReply.relations:type_name -> helloworld.v1.RelationReply
	1,  // 2: helloworld.v1.GetRelationByAccountReply.relation:type_name -> helloworld.v1.RelationReply
	1,  // 3: helloworld.v1.GetRelationByIdReply.relation:type_name -> helloworld.v1.RelationReply
	1,  // 4: helloworld.v1.GetAllRelationsReply.relations:type_name -> helloworld.v1.RelationReply
	0,  // 5: helloworld.v1.RelCusAcc.CreateRelation:input_type -> helloworld.v1.CreateRelationRequest
	3,  // 6: helloworld.v1.RelCusAcc.UpdateRelation:input_type -> helloworld.v1.UpdateRelationRequest
	5,  // 7: helloworld.v1.RelCusAcc.DeleteRelation:input_type -> helloworld.v1.DeleteRelationRequest
	7,  // 8: helloworld.v1.RelCusAcc.GetRelationsByCustomer:input_type -> helloworld.v1.GetRelationsByCustomerRequest
	9,  // 9: helloworld.v1.RelCusAcc.GetRelationByAccount:input_type -> helloworld.v1.GetRelationByAccountRequest
	13, // 10: helloworld.v1.RelCusAcc.GetAllRelations:input_type -> helloworld.v1.GetAllRelationsRequest
	2,  // 11: helloworld.v1.RelCusAcc.CreateRelation:output_type -> helloworld.v1.CreateRelationReply
	4,  // 12: helloworld.v1.RelCusAcc.UpdateRelation:output_type -> helloworld.v1.UpdateRelationReply
	6,  // 13: helloworld.v1.RelCusAcc.DeleteRelation:output_type -> helloworld.v1.DeleteRelationReply
	8,  // 14: helloworld.v1.RelCusAcc.GetRelationsByCustomer:output_type -> helloworld.v1.GetRelationsByCustomerReply
	10, // 15: helloworld.v1.RelCusAcc.GetRelationByAccount:output_type -> helloworld.v1.GetRelationByAccountReply
	14, // 16: helloworld.v1.RelCusAcc.GetAllRelations:output_type -> helloworld.v1.GetAllRelationsReply
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_rel_cus_acc_proto_init() }
func file_api_helloworld_v1_rel_cus_acc_proto_init() {
	if File_api_helloworld_v1_rel_cus_acc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_rel_cus_acc_proto_rawDesc), len(file_api_helloworld_v1_rel_cus_acc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_rel_cus_acc_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_rel_cus_acc_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_rel_cus_acc_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_rel_cus_acc_proto = out.File
	file_api_helloworld_v1_rel_cus_acc_proto_goTypes = nil
	file_api_helloworld_v1_rel_cus_acc_proto_depIdxs = nil
}
