// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/helloworld/v1/payment.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Payment messages
type CreatePaymentRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PaymentId         int64                  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	FromAccountId     int64                  `protobuf:"varint,2,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId       int64                  `protobuf:"varint,3,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	PaymentType       string                 `protobuf:"bytes,4,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	Amount            float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency          string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status            string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	PaymentMethod     string                 `protobuf:"bytes,8,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	ReferenceNumber   string                 `protobuf:"bytes,9,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	ExternalReference string                 `protobuf:"bytes,10,opt,name=external_reference,json=externalReference,proto3" json:"external_reference,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentRequest) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *CreatePaymentRequest) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *CreatePaymentRequest) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *CreatePaymentRequest) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *CreatePaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreatePaymentRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CreatePaymentRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *CreatePaymentRequest) GetExternalReference() string {
	if x != nil {
		return x.ExternalReference
	}
	return ""
}

type CreatePaymentReply struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Message           string                 `protobuf:"bytes,11,opt,name=message,proto3" json:"message,omitempty"`
	PaymentId         int64                  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	FromAccountId     int64                  `protobuf:"varint,2,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId       int64                  `protobuf:"varint,3,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	PaymentType       string                 `protobuf:"bytes,4,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	Amount            float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency          string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status            string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	PaymentMethod     string                 `protobuf:"bytes,8,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	ReferenceNumber   string                 `protobuf:"bytes,9,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	ExternalReference string                 `protobuf:"bytes,10,opt,name=external_reference,json=externalReference,proto3" json:"external_reference,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreatePaymentReply) Reset() {
	*x = CreatePaymentReply{}
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentReply) ProtoMessage() {}

func (x *CreatePaymentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentReply.ProtoReflect.Descriptor instead.
func (*CreatePaymentReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreatePaymentReply) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *CreatePaymentReply) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *CreatePaymentReply) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *CreatePaymentReply) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *CreatePaymentReply) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentReply) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreatePaymentReply) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CreatePaymentReply) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *CreatePaymentReply) GetExternalReference() string {
	if x != nil {
		return x.ExternalReference
	}
	return ""
}

type UpdatePaymentRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PaymentId         int64                  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	FromAccountId     int64                  `protobuf:"varint,2,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId       int64                  `protobuf:"varint,3,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	PaymentType       string                 `protobuf:"bytes,4,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	Amount            float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency          string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status            string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	PaymentMethod     string                 `protobuf:"bytes,8,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	ReferenceNumber   string                 `protobuf:"bytes,9,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	ExternalReference string                 `protobuf:"bytes,10,opt,name=external_reference,json=externalReference,proto3" json:"external_reference,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdatePaymentRequest) Reset() {
	*x = UpdatePaymentRequest{}
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentRequest) ProtoMessage() {}

func (x *UpdatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePaymentRequest) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *UpdatePaymentRequest) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *UpdatePaymentRequest) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *UpdatePaymentRequest) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *UpdatePaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdatePaymentRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdatePaymentRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *UpdatePaymentRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *UpdatePaymentRequest) GetExternalReference() string {
	if x != nil {
		return x.ExternalReference
	}
	return ""
}

type UpdatePaymentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Display       []*CreatePaymentReply  `protobuf:"bytes,2,rep,name=display,proto3" json:"display,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentReply) Reset() {
	*x = UpdatePaymentReply{}
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentReply) ProtoMessage() {}

func (x *UpdatePaymentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentReply.ProtoReflect.Descriptor instead.
func (*UpdatePaymentReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePaymentReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdatePaymentReply) GetDisplay() []*CreatePaymentReply {
	if x != nil {
		return x.Display
	}
	return nil
}

type DeletePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     int64                  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePaymentRequest) Reset() {
	*x = DeletePaymentRequest{}
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePaymentRequest) ProtoMessage() {}

func (x *DeletePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePaymentRequest.ProtoReflect.Descriptor instead.
func (*DeletePaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *DeletePaymentRequest) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

type DeletePaymentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePaymentReply) Reset() {
	*x = DeletePaymentReply{}
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePaymentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePaymentReply) ProtoMessage() {}

func (x *DeletePaymentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePaymentReply.ProtoReflect.Descriptor instead.
func (*DeletePaymentReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePaymentReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FindPaymentByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     int64                  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindPaymentByIdRequest) Reset() {
	*x = FindPaymentByIdRequest{}
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindPaymentByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPaymentByIdRequest) ProtoMessage() {}

func (x *FindPaymentByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPaymentByIdRequest.ProtoReflect.Descriptor instead.
func (*FindPaymentByIdRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_payment_proto_rawDescGZIP(), []int{6}
}

func (x *FindPaymentByIdRequest) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

type FindPaymentByIdReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Display       []*CreatePaymentReply  `protobuf:"bytes,1,rep,name=display,proto3" json:"display,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindPaymentByIdReply) Reset() {
	*x = FindPaymentByIdReply{}
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindPaymentByIdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPaymentByIdReply) ProtoMessage() {}

func (x *FindPaymentByIdReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPaymentByIdReply.ProtoReflect.Descriptor instead.
func (*FindPaymentByIdReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_payment_proto_rawDescGZIP(), []int{7}
}

func (x *FindPaymentByIdReply) GetDisplay() []*CreatePaymentReply {
	if x != nil {
		return x.Display
	}
	return nil
}

var File_api_helloworld_v1_payment_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/helloworld/v1/payment.proto\x12\vpayments.v1\x1a\x1cgoogle/api/annotations.proto\"\xf1\x02\n" +
	"\x14CreatePaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x03R\tpaymentId\x12&\n" +
	"\x0ffrom_account_id\x18\x02 \x01(\x03R\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x03 \x01(\x03R\vtoAccountId\x12!\n" +
	"\fpayment_type\x18\x04 \x01(\tR\vpaymentType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12%\n" +
	"\x0epayment_method\x18\b \x01(\tR\rpaymentMethod\x12)\n" +
	"\x10reference_number\x18\t \x01(\tR\x0freferenceNumber\x12-\n" +
	"\x12external_reference\x18\n" +
	" \x01(\tR\x11externalReference\"\x89\x03\n" +
	"\x12CreatePaymentReply\x12\x18\n" +
	"\amessage\x18\v \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x03R\tpaymentId\x12&\n" +
	"\x0ffrom_account_id\x18\x02 \x01(\x03R\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x03 \x01(\x03R\vtoAccountId\x12!\n" +
	"\fpayment_type\x18\x04 \x01(\tR\vpaymentType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12%\n" +
	"\x0epayment_method\x18\b \x01(\tR\rpaymentMethod\x12)\n" +
	"\x10reference_number\x18\t \x01(\tR\x0freferenceNumber\x12-\n" +
	"\x12external_reference\x18\n" +
	" \x01(\tR\x11externalReference\"\xf1\x02\n" +
	"\x14UpdatePaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x03R\tpaymentId\x12&\n" +
	"\x0ffrom_account_id\x18\x02 \x01(\x03R\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x03 \x01(\x03R\vtoAccountId\x12!\n" +
	"\fpayment_type\x18\x04 \x01(\tR\vpaymentType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12%\n" +
	"\x0epayment_method\x18\b \x01(\tR\rpaymentMethod\x12)\n" +
	"\x10reference_number\x18\t \x01(\tR\x0freferenceNumber\x12-\n" +
	"\x12external_reference\x18\n" +
	" \x01(\tR\x11externalReference\"i\n" +
	"\x12UpdatePaymentReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x129\n" +
	"\adisplay\x18\x02 \x03(\v2\x1f.payments.v1.CreatePaymentReplyR\adisplay\"5\n" +
	"\x14DeletePaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x03R\tpaymentId\".\n" +
	"\x12DeletePaymentReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"7\n" +
	"\x16FindPaymentByIdRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x03R\tpaymentId\"Q\n" +
	"\x14FindPaymentByIdReply\x129\n" +
	"\adisplay\x18\x01 \x03(\v2\x1f.payments.v1.CreatePaymentReplyR\adisplay2\xe7\x03\n" +
	"\aPayment\x12l\n" +
	"\rCreatePayment\x12!.payments.v1.CreatePaymentRequest\x1a\x1f.payments.v1.CreatePaymentReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/payments\x12y\n" +
	"\rUpdatePayment\x12!.payments.v1.UpdatePaymentRequest\x1a\x1f.payments.v1.UpdatePaymentReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*2\x19/v1/payments/{payment_id}\x12v\n" +
	"\rDeletePayment\x12!.payments.v1.DeletePaymentRequest\x1a\x1f.payments.v1.DeletePaymentReply\"!\x82\xd3\xe4\x93\x02\x1b*\x19/v1/payments/{payment_id}\x12{\n" +
	"\x0eDisplayPayment\x12#.payments.v1.FindPaymentByIdRequest\x1a!.payments.v1.FindPaymentByIdReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/payments/{payment_id}BL\n" +
	"\x1adev.kratos.api.payments.v1B\x0fPaymentsProtoV1P\x01Z\x1bpayments/api/payments/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_payment_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_payment_proto_rawDescData []byte
)

func file_api_helloworld_v1_payment_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_payment_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_payment_proto_rawDesc), len(file_api_helloworld_v1_payment_proto_rawDesc)))
	})
	return file_api_helloworld_v1_payment_proto_rawDescData
}

var file_api_helloworld_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_helloworld_v1_payment_proto_goTypes = []any{
	(*CreatePaymentRequest)(nil),   // 0: payments.v1.CreatePaymentRequest
	(*CreatePaymentReply)(nil),     // 1: payments.v1.CreatePaymentReply
	(*UpdatePaymentRequest)(nil),   // 2: payments.v1.UpdatePaymentRequest
	(*UpdatePaymentReply)(nil),     // 3: payments.v1.UpdatePaymentReply
	(*DeletePaymentRequest)(nil),   // 4: payments.v1.DeletePaymentRequest
	(*DeletePaymentReply)(nil),     // 5: payments.v1.DeletePaymentReply
	(*FindPaymentByIdRequest)(nil), // 6: payments.v1.FindPaymentByIdRequest
	(*FindPaymentByIdReply)(nil),   // 7: payments.v1.FindPaymentByIdReply
}
var file_api_helloworld_v1_payment_proto_depIdxs = []int32{
	1, // 0: payments.v1.UpdatePaymentReply.display:type_name -> payments.v1.CreatePaymentReply
	1, // 1: payments.v1.FindPaymentByIdReply.display:type_name -> payments.v1.CreatePaymentReply
	0, // 2: payments.v1.Payment.CreatePayment:input_type -> payments.v1.CreatePaymentRequest
	2, // 3: payments.v1.Payment.UpdatePayment:input_type -> payments.v1.UpdatePaymentRequest
	4, // 4: payments.v1.Payment.DeletePayment:input_type -> payments.v1.DeletePaymentRequest
	6, // 5: payments.v1.Payment.DisplayPayment:input_type -> payments.v1.FindPaymentByIdRequest
	1, // 6: payments.v1.Payment.CreatePayment:output_type -> payments.v1.CreatePaymentReply
	3, // 7: payments.v1.Payment.UpdatePayment:output_type -> payments.v1.UpdatePaymentReply
	5, // 8: payments.v1.Payment.DeletePayment:output_type -> payments.v1.DeletePaymentReply
	7, // 9: payments.v1.Payment.DisplayPayment:output_type -> payments.v1.FindPaymentByIdReply
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_payment_proto_init() }
func file_api_helloworld_v1_payment_proto_init() {
	if File_api_helloworld_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_payment_proto_rawDesc), len(file_api_helloworld_v1_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_payment_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_payment_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_payment_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_payment_proto = out.File
	file_api_helloworld_v1_payment_proto_goTypes = nil
	file_api_helloworld_v1_payment_proto_depIdxs = nil
}
