// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAccountblock = "accountblock"

// Accountblock mapped from table <accountblock>
type Accountblock struct {
	CustomerID  int64  `gorm:"column:customer_id" json:"customer_id"`
	Description string `gorm:"column:description" json:"description"`
}

// TableName Accountblock's table name
func (*Accountblock) TableName() string {
	return TableNameAccountblock
}
