// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v5.29.3
// source: api/helloworld/v1/transaction.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCardCreateTransaction = "/helloworld.v1.Card/CreateTransaction"
const OperationCardDeleteTransaction = "/helloworld.v1.Card/DeleteTransaction"
const OperationCardDisplayTransaction = "/helloworld.v1.Card/DisplayTransaction"
const OperationCardUpdateTransaction = "/helloworld.v1.Card/UpdateTransaction"

type CardHTTPServer interface {
	// CreateTransaction Transaction endpoints
	CreateTransaction(context.Context, *CreateTransactionRequest) (*CreateTransactionReply, error)
	DeleteTransaction(context.Context, *DeleteTransactionRequest) (*DeleteTransactionReply, error)
	DisplayTransaction(context.Context, *FindTransactionByIdRequest) (*FindTransactionByIdReply, error)
	UpdateTransaction(context.Context, *UpdateTransactionRequest) (*UpdateTransactionReply, error)
}

func RegisterCardHTTPServer(s *http.Server, srv CardHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/helloworld/transaction", _Card_CreateTransaction0_HTTP_Handler(srv))
	r.PATCH("/v1/helloworld/transaction/{transaction_id}", _Card_UpdateTransaction0_HTTP_Handler(srv))
	r.DELETE("/v1/helloworld/transaction/{transaction_id}", _Card_DeleteTransaction0_HTTP_Handler(srv))
	r.GET("/v1/helloworld/transaction/{transaction_id}", _Card_DisplayTransaction0_HTTP_Handler(srv))
}

func _Card_CreateTransaction0_HTTP_Handler(srv CardHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTransactionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCardCreateTransaction)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTransaction(ctx, req.(*CreateTransactionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateTransactionReply)
		return ctx.Result(200, reply)
	}
}

func _Card_UpdateTransaction0_HTTP_Handler(srv CardHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateTransactionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCardUpdateTransaction)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateTransaction(ctx, req.(*UpdateTransactionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateTransactionReply)
		return ctx.Result(200, reply)
	}
}

func _Card_DeleteTransaction0_HTTP_Handler(srv CardHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteTransactionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCardDeleteTransaction)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteTransaction(ctx, req.(*DeleteTransactionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteTransactionReply)
		return ctx.Result(200, reply)
	}
}

func _Card_DisplayTransaction0_HTTP_Handler(srv CardHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FindTransactionByIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCardDisplayTransaction)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DisplayTransaction(ctx, req.(*FindTransactionByIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FindTransactionByIdReply)
		return ctx.Result(200, reply)
	}
}

type CardHTTPClient interface {
	CreateTransaction(ctx context.Context, req *CreateTransactionRequest, opts ...http.CallOption) (rsp *CreateTransactionReply, err error)
	DeleteTransaction(ctx context.Context, req *DeleteTransactionRequest, opts ...http.CallOption) (rsp *DeleteTransactionReply, err error)
	DisplayTransaction(ctx context.Context, req *FindTransactionByIdRequest, opts ...http.CallOption) (rsp *FindTransactionByIdReply, err error)
	UpdateTransaction(ctx context.Context, req *UpdateTransactionRequest, opts ...http.CallOption) (rsp *UpdateTransactionReply, err error)
}

type CardHTTPClientImpl struct {
	cc *http.Client
}

func NewCardHTTPClient(client *http.Client) CardHTTPClient {
	return &CardHTTPClientImpl{client}
}

func (c *CardHTTPClientImpl) CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...http.CallOption) (*CreateTransactionReply, error) {
	var out CreateTransactionReply
	pattern := "/v1/helloworld/transaction"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCardCreateTransaction))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CardHTTPClientImpl) DeleteTransaction(ctx context.Context, in *DeleteTransactionRequest, opts ...http.CallOption) (*DeleteTransactionReply, error) {
	var out DeleteTransactionReply
	pattern := "/v1/helloworld/transaction/{transaction_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCardDeleteTransaction))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CardHTTPClientImpl) DisplayTransaction(ctx context.Context, in *FindTransactionByIdRequest, opts ...http.CallOption) (*FindTransactionByIdReply, error) {
	var out FindTransactionByIdReply
	pattern := "/v1/helloworld/transaction/{transaction_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCardDisplayTransaction))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CardHTTPClientImpl) UpdateTransaction(ctx context.Context, in *UpdateTransactionRequest, opts ...http.CallOption) (*UpdateTransactionReply, error) {
	var out UpdateTransactionReply
	pattern := "/v1/helloworld/transaction/{transaction_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCardUpdateTransaction))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
