// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/hello/v1/trans.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transaction messages
type CreateTransactionRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Transactionid        int64                  `protobuf:"varint,1,opt,name=transactionid,proto3" json:"transactionid,omitempty"`
	AccountId            int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	RelatedTransactionId int64                  `protobuf:"varint,3,opt,name=related_transaction_id,json=relatedTransactionId,proto3" json:"related_transaction_id,omitempty"`
	TransactionType      string                 `protobuf:"bytes,4,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	Amount               float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status               string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Description          string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ReferenceNumber      string                 `protobuf:"bytes,9,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	PostingDate          string                 `protobuf:"bytes,10,opt,name=posting_date,json=postingDate,proto3" json:"posting_date,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_api_hello_v1_trans_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hello_v1_trans_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_hello_v1_trans_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransactionRequest) GetTransactionid() int64 {
	if x != nil {
		return x.Transactionid
	}
	return 0
}

func (x *CreateTransactionRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateTransactionRequest) GetRelatedTransactionId() int64 {
	if x != nil {
		return x.RelatedTransactionId
	}
	return 0
}

func (x *CreateTransactionRequest) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *CreateTransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateTransactionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateTransactionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTransactionRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *CreateTransactionRequest) GetPostingDate() string {
	if x != nil {
		return x.PostingDate
	}
	return ""
}

type CreateTransactionReply struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Message              string                 `protobuf:"bytes,11,opt,name=message,proto3" json:"message,omitempty"`
	TransactionId        int64                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AccountId            int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	RelatedTransactionId int64                  `protobuf:"varint,3,opt,name=related_transaction_id,json=relatedTransactionId,proto3" json:"related_transaction_id,omitempty"`
	TransactionType      string                 `protobuf:"bytes,4,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	Amount               float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status               string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Description          string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ReferenceNumber      string                 `protobuf:"bytes,9,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	PostingDate          string                 `protobuf:"bytes,10,opt,name=posting_date,json=postingDate,proto3" json:"posting_date,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateTransactionReply) Reset() {
	*x = CreateTransactionReply{}
	mi := &file_api_hello_v1_trans_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionReply) ProtoMessage() {}

func (x *CreateTransactionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_hello_v1_trans_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionReply.ProtoReflect.Descriptor instead.
func (*CreateTransactionReply) Descriptor() ([]byte, []int) {
	return file_api_hello_v1_trans_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTransactionReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateTransactionReply) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *CreateTransactionReply) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateTransactionReply) GetRelatedTransactionId() int64 {
	if x != nil {
		return x.RelatedTransactionId
	}
	return 0
}

func (x *CreateTransactionReply) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *CreateTransactionReply) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionReply) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateTransactionReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateTransactionReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTransactionReply) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *CreateTransactionReply) GetPostingDate() string {
	if x != nil {
		return x.PostingDate
	}
	return ""
}

type UpdateTransactionRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TransactionId        int64                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AccountId            int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	RelatedTransactionId int64                  `protobuf:"varint,3,opt,name=related_transaction_id,json=relatedTransactionId,proto3" json:"related_transaction_id,omitempty"`
	TransactionType      string                 `protobuf:"bytes,4,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	Amount               float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status               string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Description          string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ReferenceNumber      string                 `protobuf:"bytes,9,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	PostingDate          string                 `protobuf:"bytes,10,opt,name=posting_date,json=postingDate,proto3" json:"posting_date,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateTransactionRequest) Reset() {
	*x = UpdateTransactionRequest{}
	mi := &file_api_hello_v1_trans_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionRequest) ProtoMessage() {}

func (x *UpdateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hello_v1_trans_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionRequest.ProtoReflect.Descriptor instead.
func (*UpdateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_hello_v1_trans_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTransactionRequest) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *UpdateTransactionRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateTransactionRequest) GetRelatedTransactionId() int64 {
	if x != nil {
		return x.RelatedTransactionId
	}
	return 0
}

func (x *UpdateTransactionRequest) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *UpdateTransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateTransactionRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateTransactionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateTransactionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTransactionRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *UpdateTransactionRequest) GetPostingDate() string {
	if x != nil {
		return x.PostingDate
	}
	return ""
}

type UpdateTransactionReply struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Message       string                    `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Display       []*CreateTransactionReply `protobuf:"bytes,2,rep,name=display,proto3" json:"display,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransactionReply) Reset() {
	*x = UpdateTransactionReply{}
	mi := &file_api_hello_v1_trans_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionReply) ProtoMessage() {}

func (x *UpdateTransactionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_hello_v1_trans_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionReply.ProtoReflect.Descriptor instead.
func (*UpdateTransactionReply) Descriptor() ([]byte, []int) {
	return file_api_hello_v1_trans_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTransactionReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateTransactionReply) GetDisplay() []*CreateTransactionReply {
	if x != nil {
		return x.Display
	}
	return nil
}

type DeleteTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId int64                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionRequest) Reset() {
	*x = DeleteTransactionRequest{}
	mi := &file_api_hello_v1_trans_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionRequest) ProtoMessage() {}

func (x *DeleteTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hello_v1_trans_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionRequest.ProtoReflect.Descriptor instead.
func (*DeleteTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_hello_v1_trans_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteTransactionRequest) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

type DeleteTransactionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionReply) Reset() {
	*x = DeleteTransactionReply{}
	mi := &file_api_hello_v1_trans_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionReply) ProtoMessage() {}

func (x *DeleteTransactionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_hello_v1_trans_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionReply.ProtoReflect.Descriptor instead.
func (*DeleteTransactionReply) Descriptor() ([]byte, []int) {
	return file_api_hello_v1_trans_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTransactionReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FindTransactionByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId int64                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindTransactionByIdRequest) Reset() {
	*x = FindTransactionByIdRequest{}
	mi := &file_api_hello_v1_trans_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindTransactionByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTransactionByIdRequest) ProtoMessage() {}

func (x *FindTransactionByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hello_v1_trans_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTransactionByIdRequest.ProtoReflect.Descriptor instead.
func (*FindTransactionByIdRequest) Descriptor() ([]byte, []int) {
	return file_api_hello_v1_trans_proto_rawDescGZIP(), []int{6}
}

func (x *FindTransactionByIdRequest) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

type FindTransactionByIdReply struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Display       []*CreateTransactionReply `protobuf:"bytes,1,rep,name=display,proto3" json:"display,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindTransactionByIdReply) Reset() {
	*x = FindTransactionByIdReply{}
	mi := &file_api_hello_v1_trans_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindTransactionByIdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTransactionByIdReply) ProtoMessage() {}

func (x *FindTransactionByIdReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_hello_v1_trans_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTransactionByIdReply.ProtoReflect.Descriptor instead.
func (*FindTransactionByIdReply) Descriptor() ([]byte, []int) {
	return file_api_hello_v1_trans_proto_rawDescGZIP(), []int{7}
}

func (x *FindTransactionByIdReply) GetDisplay() []*CreateTransactionReply {
	if x != nil {
		return x.Display
	}
	return nil
}

var File_api_hello_v1_trans_proto protoreflect.FileDescriptor

const file_api_hello_v1_trans_proto_rawDesc = "" +
	"\n" +
	"\x18api/hello/v1/trans.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"\xfc\x02\n" +
	"\x18CreateTransactionRequest\x12$\n" +
	"\rtransactionid\x18\x01 \x01(\x03R\rtransactionid\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x124\n" +
	"\x16related_transaction_id\x18\x03 \x01(\x03R\x14relatedTransactionId\x12)\n" +
	"\x10transaction_type\x18\x04 \x01(\tR\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12)\n" +
	"\x10reference_number\x18\t \x01(\tR\x0freferenceNumber\x12!\n" +
	"\fposting_date\x18\n" +
	" \x01(\tR\vpostingDate\"\x95\x03\n" +
	"\x16CreateTransactionReply\x12\x18\n" +
	"\amessage\x18\v \x01(\tR\amessage\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x03R\rtransactionId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x124\n" +
	"\x16related_transaction_id\x18\x03 \x01(\x03R\x14relatedTransactionId\x12)\n" +
	"\x10transaction_type\x18\x04 \x01(\tR\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12)\n" +
	"\x10reference_number\x18\t \x01(\tR\x0freferenceNumber\x12!\n" +
	"\fposting_date\x18\n" +
	" \x01(\tR\vpostingDate\"\xfd\x02\n" +
	"\x18UpdateTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x03R\rtransactionId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x124\n" +
	"\x16related_transaction_id\x18\x03 \x01(\x03R\x14relatedTransactionId\x12)\n" +
	"\x10transaction_type\x18\x04 \x01(\tR\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12)\n" +
	"\x10reference_number\x18\t \x01(\tR\x0freferenceNumber\x12!\n" +
	"\fposting_date\x18\n" +
	" \x01(\tR\vpostingDate\"s\n" +
	"\x16UpdateTransactionReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12?\n" +
	"\adisplay\x18\x02 \x03(\v2%.helloworld.v1.CreateTransactionReplyR\adisplay\"A\n" +
	"\x18DeleteTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x03R\rtransactionId\"2\n" +
	"\x16DeleteTransactionReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"C\n" +
	"\x1aFindTransactionByIdRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x03R\rtransactionId\"[\n" +
	"\x18FindTransactionByIdReply\x12?\n" +
	"\adisplay\x18\x01 \x03(\v2%.helloworld.v1.CreateTransactionReplyR\adisplay2\xf3\x04\n" +
	"\vTransaction\x12\x8a\x01\n" +
	"\x11CreateTransaction\x12'.helloworld.v1.CreateTransactionRequest\x1a%.helloworld.v1.CreateTransactionReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/helloworld/transaction\x12\x9b\x01\n" +
	"\x11UpdateTransaction\x12'.helloworld.v1.UpdateTransactionRequest\x1a%.helloworld.v1.UpdateTransactionReply\"6\x82\xd3\xe4\x93\x020:\x01*2+/v1/helloworld/transaction/{transaction_id}\x12\x98\x01\n" +
	"\x11DeleteTransaction\x12'.helloworld.v1.DeleteTransactionRequest\x1a%.helloworld.v1.DeleteTransactionReply\"3\x82\xd3\xe4\x93\x02-*+/v1/helloworld/transaction/{transaction_id}\x12\x9d\x01\n" +
	"\x12DisplayTransaction\x12).helloworld.v1.FindTransactionByIdRequest\x1a'.helloworld.v1.FindTransactionByIdReply\"3\x82\xd3\xe4\x93\x02-\x12+/v1/helloworld/transaction/{transaction_id}BU\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z transaction/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_hello_v1_trans_proto_rawDescOnce sync.Once
	file_api_hello_v1_trans_proto_rawDescData []byte
)

func file_api_hello_v1_trans_proto_rawDescGZIP() []byte {
	file_api_hello_v1_trans_proto_rawDescOnce.Do(func() {
		file_api_hello_v1_trans_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_hello_v1_trans_proto_rawDesc), len(file_api_hello_v1_trans_proto_rawDesc)))
	})
	return file_api_hello_v1_trans_proto_rawDescData
}

var file_api_hello_v1_trans_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_hello_v1_trans_proto_goTypes = []any{
	(*CreateTransactionRequest)(nil),   // 0: helloworld.v1.CreateTransactionRequest
	(*CreateTransactionReply)(nil),     // 1: helloworld.v1.CreateTransactionReply
	(*UpdateTransactionRequest)(nil),   // 2: helloworld.v1.UpdateTransactionRequest
	(*UpdateTransactionReply)(nil),     // 3: helloworld.v1.UpdateTransactionReply
	(*DeleteTransactionRequest)(nil),   // 4: helloworld.v1.DeleteTransactionRequest
	(*DeleteTransactionReply)(nil),     // 5: helloworld.v1.DeleteTransactionReply
	(*FindTransactionByIdRequest)(nil), // 6: helloworld.v1.FindTransactionByIdRequest
	(*FindTransactionByIdReply)(nil),   // 7: helloworld.v1.FindTransactionByIdReply
}
var file_api_hello_v1_trans_proto_depIdxs = []int32{
	1, // 0: helloworld.v1.UpdateTransactionReply.display:type_name -> helloworld.v1.CreateTransactionReply
	1, // 1: helloworld.v1.FindTransactionByIdReply.display:type_name -> helloworld.v1.CreateTransactionReply
	0, // 2: helloworld.v1.Transaction.CreateTransaction:input_type -> helloworld.v1.CreateTransactionRequest
	2, // 3: helloworld.v1.Transaction.UpdateTransaction:input_type -> helloworld.v1.UpdateTransactionRequest
	4, // 4: helloworld.v1.Transaction.DeleteTransaction:input_type -> helloworld.v1.DeleteTransactionRequest
	6, // 5: helloworld.v1.Transaction.DisplayTransaction:input_type -> helloworld.v1.FindTransactionByIdRequest
	1, // 6: helloworld.v1.Transaction.CreateTransaction:output_type -> helloworld.v1.CreateTransactionReply
	3, // 7: helloworld.v1.Transaction.UpdateTransaction:output_type -> helloworld.v1.UpdateTransactionReply
	5, // 8: helloworld.v1.Transaction.DeleteTransaction:output_type -> helloworld.v1.DeleteTransactionReply
	7, // 9: helloworld.v1.Transaction.DisplayTransaction:output_type -> helloworld.v1.FindTransactionByIdReply
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_hello_v1_trans_proto_init() }
func file_api_hello_v1_trans_proto_init() {
	if File_api_hello_v1_trans_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_hello_v1_trans_proto_rawDesc), len(file_api_hello_v1_trans_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_hello_v1_trans_proto_goTypes,
		DependencyIndexes: file_api_hello_v1_trans_proto_depIdxs,
		MessageInfos:      file_api_hello_v1_trans_proto_msgTypes,
	}.Build()
	File_api_hello_v1_trans_proto = out.File
	file_api_hello_v1_trans_proto_goTypes = nil
	file_api_hello_v1_trans_proto_depIdxs = nil
}
